### ISSUE TITLE
System-Components BEM Composition?

### ISSUE THREAD

**Issue by JoshRosenstein** [jxnblk/styled-system#109]
I'm trying to create some components and have a Block.Element structure,
In the example attached I have 
```
const Grid = system(
  'width',
  'space',
  'fontSize',
  'color',
  'size',
  'overflow',
  'gridContainer',
  { display: 'grid' }
)

export const GridItem = system('size', 'gridItems')

export default Grid
```
But want to export GridItem attached to grid like:
```
const Grid = system(
  'width',
  'space',
  'fontSize',
  'color',
  'size',
  'overflow',
  'gridContainer',
  { display: 'grid' }
)

Grid.Item = system('size', 'gridItems')

export default Grid
```
Is that possible or do we lose that capability passing through system?

[![Edit cssgrid-styled](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/v6oxmlx790)

**Comment by jxnblk** [comment]
This should work since `Grid.Item` will still be a styled-component - are you encountering any issues?

**Comment by JoshRosenstein** [comment]
hmm just changed my code back and it decided not to throw an error now. Working now, sorry about that. Thanks
