### ISSUE TITLE
Use styled functions in complexStyle

### ISSUE THREAD

**Issue by johno** [jxnblk/styled-system#116]
I've been finding `complexStyle` to be quite useful for a few use cases, like button sizing. However, I'm wondering if it might be nice to provide styled function shorthand/usage.

Currently something like this doesn't work:

```js
const buttonSizes = {
  small: {
    py: 2,
    px: 3,
    fontSize: 0,
  },
  normal: {
    py: 3,
    px: 4,
    fontSize: 1
  },
  large: {
    py: 4,
    px: 5,
   fontSize: 2
  }
}
```

Of course, we can work around it by grabbing from our other objects in `theme.js` and manually calling `util.px` or hardcoding values:

```js
import { util } from 'styled-system'

const buttonSizes = {
  small: {
    padding: [space[2], space[3]].map(util.px).join(' '),
    fontSize: '12px'
   }
  // ...
}
```

Though, to me, this feels a little clunky. Would it be more ergonomic to pass through styled functions, or perhaps optionally pass them in?

```js
import {
  complexStyle,
  fontSize,
  space
} from 'styled-system'

const size = complexStyle({
  prop: 'size',
  key: 'buttonSizes',
  // Pass in functions to transform properties
  systems: [fontSize, space]
})
```

Another option might be piping:

```js
import {
  complexStyle,
  fontSize,
  space,
  util
} from 'styled-system'

const size = complexStyle({
  prop: 'size',
  key: 'buttonSizes',
  // Pass in functions to transform properties
  systems: [fontSize, space]
})

export default styled.button`
  ${util.pipe(size, fontSize, space)}
`
```

**Comment by jxnblk** [comment]
I've thought about this a little bit, but would be good to figure out a good solution for this.

On one hand, I think it's potentially confusing (or even more confusing than this library already is) to mix props with style objects, so in doing something like this, I'd want to make sure that they are actually separate objects. On the other hand, I'm sure people will want this functionality, and it seems sort of expected.

If there's a props function that returns other props, it's really not that different than [mapProps](https://github.com/acdlite/recompose/blob/master/docs/API.md#mapprops), right?

The other thought with the current API, is that if these "complex style" objects are created in the same theme module as the other values, it should be that hard to reference the values directly

**Comment by samtietjen** [comment]
I've also been trying to figure this out.

What makes complex styles so great is they let you get more specific with your definitions. A warning color style isn't a single color, it's a combination of a foreground and background color. I feel like it makes sense for these two colors to respect the array of colors defined by the system.

This makes the most sense to me when setting element styles. When I'm defining a primary button I'm not really looking to make something new, I'm looking to get more specific. The primary button should respect the color object and the other low level theme properties. Almost more like a series of presets. Of course you could just reference the color object directly for each color, but I'm wondering if there's a more elegant way.

Am I making any sense?

**Comment by jxnblk** [comment]
Closing this out – I think I'd like to keep the core a little more focused and not conflate props and style objects
