### ISSUE TITLE
PropTypes as peerDependancy

### ISSUE THREAD

**Issue by GazzaHazza** [jxnblk/styled-system#117]
Should `prop-types` be a `peerDependency` instead of a `dependency`?

**Comment by jxnblk** [comment]
https://github.com/facebook/prop-types/blob/master/README.md#how-to-depend-on-this-package

Not according to the docs

**Comment by sshmyg** [comment]
@jxnblk So you should  include "babel-plugin-transform-react-remove-prop-types" this plugin to remove prop-types from prod build.
