### ISSUE TITLE
fontSize prop renders to font-size attribute

### ISSUE THREAD

**Issue by selrond** [jxnblk/styled-system#123]
When using `${fontSize}` function in my custom component, such as 

```jsx
<H1 fontSize="2em">
	Something...
</H1>
```

React apparently treats is as HTML attribute and renders it as `font-size` on the respective tag.

```jsx
<h1 font-size="2em">
	Something...
</h1>
```

What can be done to override / circumvent this behavior

**Comment by selrond** [comment]
Just noticed it's the same behavior with color:

```jsx
<H1 color="red">
	Something...
</H1>
```

renders to

```jsx
<h1 color="red">
	Something...
</h1>
```

It _does_ add the color (and font-size) to the styles properly, but I guess it shouldn't leak it to HTML tags.

**Comment by jxnblk** [comment]
See this and let me know if that helps https://github.com/jxnblk/styled-system/blob/master/README.md#troubleshooting

**Comment by jxnblk** [comment]
It’s sort of a long standing issue with styled-components and how it whitelists html attributes

**Comment by selrond** [comment]
I've looked at it a few times, not quite sure how to apply it. Will give it a try

**Comment by eugenkiss** [comment]
Do [`clean-element`](https://github.com/jxnblk/styled-system/tree/master/clean-element) or [`clean-tag`](https://github.com/jxnblk/styled-system/tree/master/clean-tag) work as intended for anybody? For me, they do not change the behavior wrt. to e.g. `fontSize`.

**Comment by selrond** [comment]
@eugenkiss could you provide a code example?

**Comment by jxnblk** [comment]
Added an example here: https://github.com/jxnblk/styled-system/tree/examples/examples/clean

Also, please let me know how we could make the docs better here: https://github.com/jxnblk/styled-system/tree/master/clean-tag

**Comment by selrond** [comment]
@jxnblk wait - where is it defined what an actual HTML element `<Text>` is going to be in [your example](https://github.com/jxnblk/styled-system/tree/examples/examples/clean)?

Sorry for noobish question, but it really doesn't make sense to me

**Comment by eugenkiss** [comment]
Thanks a lot for your example @jxnblk. I just ran it locally and found my issue. I didn't set a custom theme. When I use `ThemeProvider` with a custom `theme` in my project everything works as expected. 

What I did: I removed `<ThemeProvider theme={theme}>` from the `App` in the example. I thought that in that case the default theme will take over which seems to have [`fontSizes` defined](https://github.com/jxnblk/styled-system/blob/04568084187b612e72d5b0e6cedb18c60a010bb5/src/constants.js). Do you know why the `defaultTheme` doesn't take over in this situation?

**Comment by selrond** [comment]
@jxnblk Or - how can I use say h1 instead of default `<div>` in `clean-tag`?

**Comment by selrond** [comment]
@jxnblk ok I got it finally! Seems to work!

It'd be really good to have some basic documentation for `clean-tag` in place. I could try to put together something quick

**Comment by jxnblk** [comment]
clean-tag accepts an `is` prop for the element, but you can also use something like `Tag.h2` in the component definition. And yeah, noticed the missing default font sizes thing, so that’s a bug

**Comment by selrond** [comment]
@jxnblk awesome! Exactly what I wanted!

**Comment by selrond** [comment]
@jxnblk by the way - why there's no GitHub repo for your `clean-tag` NPM package?

**Comment by jxnblk** [comment]
This is a monorepo, so that package is in this repo, in the `clean-tag/` folder
