### ISSUE TITLE
2 Feature Suggestions: Attach input args to output for style functions. & Optional 'styles' arg for system-components

### ISSUE THREAD

**Issue by JoshRosenstein** [jxnblk/styled-system#131]
@jxnblk 
just a thought: attaching the arguments in the style functions like you do with proptypes, will allow an easier way to document the default styles and user custom styles. 
Also, it will be nice to make system-components, take in an optional 'styles'  argument on create (fallbacks to styled-system styles), that way we can feed in custom styles to the dict. 
![outputinputargs](https://user-images.githubusercontent.com/32781407/36577269-47c2ddce-1824-11e8-93d1-e04141296f27.PNG)

**Comment by JoshRosenstein** [comment]
Adding another idea...
Hit a bit of a road block when trying to use StyledComponent Parent that needed to pass down to a styled child and not lose the functionality of being able to extend the child. So instead of something like this below
````
const Component= ({ children,sharedProps, innerRef, ...props }) => (
  <Parent {...props, ...sharedProps}>
  <Child ...sharedProps>
children
</Child>
  </Parent>
)
````
I can do 
````
const Parent = styled(tag)`
${fn(prop1))
`
Parent.defaultProps{
is:div
theme:theme,
passProps:['prop1','prop2','theme']}

Parent.Child=styled(tag)`
${fn2(prop1)) ${fn3(prop2))
`
Parent.Child.defaultProps{
is:...
}
````

By changing the tag function to something like:
````
export class Tag extends React.Component {
  render() {
    const {
      innerRef,
      is,
      blacklist,
      children,
      passProp,
      theme,
      ...props
    } = this.props
    const attr = omit(props, blacklist)
    const propsToChildren = pick(passProp, props)
    const getChildren = () => {
      let childrenCount = React.Children.count(children)
      if (childrenCount > 1 && !isEmpty(propsToChildren)) {
        return React.Children.map(children, (child, i) => {
          if (i < 20) {
            ///Temporary Guager for testing
            if (typeof child === 'object') {
              ///Look to see if i can be more specific of the type of child
              return React.cloneElement(
                child,
                merge(child.props, propsToChildren) ///Need to see if it only overides defaultP and not
              )
            }
          }

          return child
        })
      } else {
        return children
      }
    }

    return React.createElement(
      is,
      {
        ref: innerRef,
        ...attr
      },
      getChildren()
    )
  }
}

Tag.defaultProps = {
  is: 'div',
  blacklist,
  passProp: ['dummy']
}

````

This might be a one off instance where a parent and a child share same prop, but return different css according to the prop, but this makes it cleaner so i dont have to duplicate the prop for each child like:

````
<Parent spacing='sm'>
<Parent.Child spacing='sm'> </Parent.Child>
<Parent.Child spacing='sm'></Parent.Child>
<Parent.Child spacing='lg'></Parent.Child>
</Parent>
`````
And now I dont have to pass the prop down to each child, and i have the abililty to extend the styles of styled Child, where you cant extend if you have a single wrapper component. And I have the ability of overriding the passed prop on the child.
````
<Parent spacing='sm'>
<Parent.Child> </Parent.Child>
<Parent.Child></Parent.Child>
<Parent.Child spacing='lg'></Parent.Child>
</Parent>
`````

Just thought I'd share.. and appreciate any feedback or if theres any potential problems doing this

**Comment by jxnblk** [comment]
Sorry for never chiming in on this, but sounds like this is similar to what I've started here: https://github.com/jxnblk/styled-system/tree/master/system-docs

Going to close this issue out, but feel free to open a new one if relevant
