### ISSUE TITLE
using `...typography.propTypes` throws an error

### ISSUE THREAD

**Issue by selrond** [jxnblk/styled-system#132]
Basic example:

```js
import { space, fontSize, color, typography } from 'styled-system'
import Tag from 'clean-tag'

const StyledH1 = styled(Tag.h1)`
	${space};
	${fontSize};
	${color};
	${typography};
`
export const H1 = ({ children, ...rest }) => (
	<StyledH1 {...rest}>
		{children}
	</StyledH1>
)
```

then adding propTypes: 

```js
H1.propTypes = {
	children: PropTypes.node.isRequired,
	...space.propTypes,
	...fontSize.propTypes,
	...color.propTypes
}
```

everything's fine, but when `...typography.propTypes` is added

```js
H1.propTypes = {
	children: PropTypes.node.isRequired,
	...space.propTypes,
	...fontSize.propTypes,
	...color.propTypes,

	// This causes TypeError
	...typography.propTypes
}
```

TypeError is thrown:

![image](https://user-images.githubusercontent.com/6603389/36590584-69b7aebc-188f-11e8-8bdc-6af6609dbb99.png)

**Comment by jxnblk** [comment]
Sorry, it's probably not clear from the current docs, but `typography` is not an export. Here's the list of functions and their props:

https://github.com/jxnblk/styled-system#table-of-style-props

**Comment by selrond** [comment]
@jxnblk then it'd be best to mention it explicitly in [proptypes section](https://github.com/jxnblk/styled-system#proptypes)

Currently it says

> Prop type definitions are available for each style function to add to your component's propTypes object.
