### ISSUE TITLE
Difference with design-system-utils?

### ISSUE THREAD

**Issue by muhajirframe** [jxnblk/styled-system#135]
I'd love to know the difference of https://github.com/mrmartineau/design-system-utils/ with syled-system
Is it similiar or have different goals?

**Comment by jxnblk** [comment]
Sorry I haven't tried that library personally. Styled System is focused on utilities for style props that hook into theme values and applying styles in a mobile-first responsive way. Please let me know if there's anything that would help clarify what this library does in the README.md
