### ISSUE TITLE
Missing babel-runtime dependency?

### ISSUE THREAD

**Issue by rybesh** [jxnblk/styled-system#136]
It seems that `styled-system` requires `babel-runtime`, but it is not listed as a dependency in `package.json`. When I try to run an example without it, I get:
```
Error: Cannot find module 'babel-runtime/core-js/object/keys'
    at styled-system/dist/index.js:8:13
```

**Comment by rybesh** [comment]
I'm not using babel-loader; I'm actually trying to de-babelify a project of mine that used an older version of rebass, which is how I ran into this.

**Comment by hendrul** [comment]
I can't use the library in expo snack because of this, it throws 
`Failed to install module 'styled-system': Attempted to import missing module 'babel-runtime/core-js/object/keys'`

**Comment by duro** [comment]
I'm having same issue trying to use in a react-native project that uses TypeScript (no babel). Is there a workaround?

**Comment by duro** [comment]
I actually tried adding the stage-0 plugin to my own deps, and that did not get me anywhere.

@hendrul Did you get anywhere with getting `styled-system` integrated into your RN project?

**Comment by hendrul** [comment]
@duro yes, I could use it in a react-native app. But I love expo snack, and I use it for every component/screen I make and sadly expo snack doesn't works with this lib because of this dependency babel-runtime

**Comment by hendrul** [comment]
But I think it's the expo's fault anyway.
