### ISSUE TITLE
feature - add ability to define spacing function

### ISSUE THREAD

**Issue by selrond** [jxnblk/styled-system#137]
Would it be possible to define spacing function instead of hand-coding values into array?

instead of 

```jsx
const space = [4, 8, 12, 16, 20, 24, 28, ...]
```

could be

```jsx
const space = n => (n * 4)
```

**Comment by jxnblk** [comment]
You could generate the array programmatically with what you have above, e.g. `Array.from({ length: 12 }).map((n, i) => i).map(space)` or you can make a custom function using `responsiveStyles` with a custom `getter` method
