### ISSUE TITLE
Why are certain functions not responsive?

### ISSUE THREAD

**Issue by quicksnap** [jxnblk/styled-system#141]
I'm experimenting with some code patterns and noticed that `borderColor` isn't responsive, even though the basic `color` is. 

Why are certain functions non-responsive?

**Comment by jxnblk** [comment]
Partly because the original library only included `width`, `fontSize`, `color`, and `space` and keeping it parallel seemed better. Handling responsive styles is a little less performant, so I opted to make some functions that didn't seem useful as responsive props a little simpler

**Comment by quicksnap** [comment]
Awesome! Thanks. I tested out the `responsiveStyle` method and it's really simple to just create my own.

Great work on all this! Thanks.
