### ISSUE TITLE
system-components causes `className` React hydration bug in isomorphic applications

### ISSUE THREAD

**Issue by ryardley** [jxnblk/styled-system#158]
It appears that `system-components` causes a React hydration bug in isomorphic applications.

![image](https://user-images.githubusercontent.com/1256409/37629055-9aeb9f2a-2c30-11e8-9b35-22fbcd7e8203.png)

This was happening on our custom isomorphic application however it was easy to create an example in a vanilla next.js application.

https://github.com/ryardley/isomorphic-bug-in-system-components

## This causes the error

```jsx
import system from 'system-components';

const Box = system({
  p: 2,
  bg: 'red',
});
Box.displayName = 'Box'; // Attempts at setting displayName does not help or change anything

export default () => <Box>This causes an error!</Box>;
```

## Normal styled components works fine

```jsx
import styled, {ThemeProvider} from 'styled-components';

const Box = styled.div`
  padding: 8px;
  background-color: green;
`;

export default () => <Box>This causes no error!</Box>;
```

All this is with the appropriate SSR setting on the `babel-plugin-styled-components`: 

```json
{
  "presets": ["next/babel"],
  "plugins": [["babel-plugin-styled-components", {
    "ssr": true
  }]]
}
```

**Comment by ryardley** [comment]
On further investigation it appears we can simulate the error by invoking styled-components by passing styled-components using the array and arguments syntax.

```
// This causes the error
styled.div([], space, color);
```

```
// This does not cause the error
styled.div(`${space}${color}`);
```

**Comment by iam4x** [comment]
Do you have an idea what is the issue underneath @jx	? Would love to help to fix this.

**Comment by ryardley** [comment]
@iam4x There is some more context here https://github.com/styled-components/babel-plugin-styled-components/issues/133 even though this is an upstream bug it would be possible for this lib to work around it.

**Comment by ckeeney** [comment]
There is discussion in the styled-components repo of deprecating the `StyledComponent.extend` api in favor of `styled(StyledComponent)`.  I'm not sure if this would also affect the api for styling native DOM elements like `styled.div`.

**Comment by jxnblk** [comment]
I've moved system-components to https://github.com/rebassjs/components so closing this issue out
