### ISSUE TITLE
Add a show or hide function

### ISSUE THREAD

**Issue by ckeeney** [jxnblk/styled-system#161]
https://github.com/jxnblk/hidden-styled exists for easily hiding things responsively, but it isn't compatible with the breakpoints defined in `styled-system`.  

There was also the related feature request for `grid-styled`: https://github.com/jxnblk/grid-styled/issues/39.  

There is a related PR for `rebass`: https://github.com/jxnblk/rebass/pull/373

I think it's reasonable for `styled-system` to export a `show` utility function:

```js
export const show = responsiveStyle({
    prop: 'show',
    cssProperty: 'display',
    numberToPx: false,
    getter: n => n ? 'block' : 'none',
});

// usage:

const MobileMenu = Box.extend`
    ${show}
`
const DesktopMenu= Box.extend`
    ${show}
`

const MyMenu = () => (
    <Box>
        <DesktopMenu show={[0, 0, 1]}/>
        <MobileMenu show={[1, 1, 0]}/>
    </Box>
)
```

I created a `Show` function because to me, it's more intuitive to describe when something is visible rather than when something is hidden.  I'm open to other APIs, but wanted to open the discussion.

**Comment by jessehart** [comment]
why not just use the responsive `display` prop?

**Comment by jxnblk** [comment]
Agree with @jessehart here, I think the `display` function should handle this case and is more inline with CSS syntax

**Comment by ckeeney** [comment]
I agree that the `display` function also meets this need, but just thought the syntax was a little more intuitive and more in line with what people were trying to accomplish with

- https://github.com/jxnblk/rebass/pull/373
- https://github.com/jxnblk/grid-styled/issues/39
- https://github.com/jxnblk/hidden-styled

Feel free to close this issue as won't fix if the idea is rejected.  I'm happy just knowing the idea is documented here.
