### ISSUE TITLE
[Question]: why is lineHeight not responsive?

### ISSUE THREAD

**Issue by harrisrobin** [jxnblk/styled-system#162]
Hello,

I really love this library, I have been using it on all my projects however I always find myself making a responsive lineHeight.. very useful and goes very well with fontSize={[...]}. Usually you need different lineHeights for different breakpoints so am I miss understanding something?

Thanks for everything, let me know if i can help with a PR!

**Comment by harrisrobin** [comment]
@brandtnew i simply use `responsiveStyle`

```js
const lineHeight = responsiveStyle({
  prop: "lineHeight",
  cssProperty: "lineHeight"
})
```

**Comment by jxnblk** [comment]
Related jxnblk/rebass#377

**Comment by jxnblk** [comment]
It's not something I commonly use, but I'd accept a PR to make the lineHeight function responsive

**Comment by jessehart** [comment]
i can see this being an issue if you're not using unitless line heights. but in that case, why?! :)

**Comment by harrisrobin** [comment]
@jessehart I often follow designs from Sketch files that have very specific line heights on desktop and mobile, and i found that to get it pixel perfect I was better off simply copy pasting the "PX" value and adding breakpoints rather than trying to estimate it with a unitless line-height. Regardless, I think this lib should provide the option.

@jxnblk sounds good, ill see what i can do later today!
