### ISSUE TITLE
TypeError: (0 , _styledSystem.removeProps) is not a function

### ISSUE THREAD

**Issue by jonleopard** [jxnblk/styled-system#164]
Hi! I just upgraded the styled-system package today from 1.1.1 to 2.2.1, and now I am getting the following TypeError:

```
TypeError: (0 , _styledSystem.removeProps) is not a function

new BaseComponent
src/components/typography.js:7

   4 | import { Box } from 'grid-styled';
   5 | 
   6 | const BaseComponent = props => {
>  7 |   const next = removeProps(props);
   8 |   return <Box {...next} />;
   9 | };
  10 | 
```
Here's my Wrapper:

```
const BaseComponent = props => {
  const next = removeProps(props);
  return <Box {...next} />;
};
```

Has anything changed with removeProps?

**Comment by jxnblk** [comment]
The `removeProps` method was removed in v2 (see https://github.com/jxnblk/styled-system/releases/tag/v2.0.0) – instead you can use one of these packages:
- https://github.com/jxnblk/styled-system/tree/master/clean-tag
- https://github.com/jxnblk/styled-system/tree/master/clean-element

**Comment by jonleopard** [comment]
Ah, great! Thanks @jxnblk 😁
