### ISSUE TITLE
[Question]: Shorthand props

### ISSUE THREAD

**Issue by benjamingeorge** [jxnblk/styled-system#166]
What is the most succinct way to accomplish shorthand props such as 
```jsx
<Text bold center>some title text</Text>
```

instead of 

```jsx
<Text fontWeight="bold" textAlign="center">some title text</Text>
```

having them result in styles like

```css
font-weight: bold;
text-align: center;
```

**Comment by Tilican** [comment]
hi,
see this repo : https://github.com/diegohaz/styled-theme & https://github.com/diegohaz/styled-tools :)

**Comment by jxnblk** [comment]
Currently styled-system uses string values (not booleans) for enum types. You could use a custom function to achieve what you suggest, but what would you imagine happening when someone did something like `<Text center right />`?
