### ISSUE TITLE
Set height 100% ? 

### ISSUE THREAD

**Issue by nicolasletoublon** [jxnblk/styled-system#167]
Hi guys, maybe I should raise the problem I'm having somewhere else but I can't figure out a way to put a height 100% on my component. width={1} works great, but what about height ? 
Thanks !

**Comment by jessehart** [comment]
`height='100%'` ?

**Comment by davidyeiser** [comment]
I ran into this as well, needed to set an element’s height to 100%. `height={ 1/1 }` returned `1px` whereas I would expect it to return `100%` like the `width` property. Was this intentional? If not I can try to submit a fix.
