### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by chetmurphy** [jxnblk/styled-system#169]
Is it possible to add typescript support?

**Comment by harrisrobin** [comment]
@chetmurphy right now it does not, however I did find and end up using this:

https://github.com/mujuni88/react-typescript-mobx-antd/blob/master/src/%40types/styled-system/index.d.ts

**Comment by chetmurphy** [comment]
I found a different copy, but I am not convinced  that it is correct.  For example width is defined as

export function width(...args: any[]): any;

so when it is used

export const Container = styled.div`
  width: 100%;

then any value is valid. No type checking or autocomplete. It is also incomplete (does not contain all properties in styled-system).

To be fair there is also a typescript bug Allow type arguments in generic tagged templates #23430<https://github.com/Microsoft/TypeScript/pull/23430> that prevents overriding/merging types that is common in styled-system. A fix has been proposed but has not yet been integrated.

**Comment by phobon** [comment]
So, I'm going to submit a PR with a more fleshed out version of what @harrisrobin linked... It works, but to use with a library like styled-components, you've got to use something like [styled-components-ts](https://www.npmjs.com/package/styled-components-ts). I've been using that combination like this:

````js
import styled from 'styled-components';
import styledTs from 'styled-components-ts';
import { width, space, WidthProps, SpaceProps } from 'styled-system';

type BoxProps = WidthProps & SpaceProps;

const Box = styledTs<BoxProps>(styled.div)`
   ${width}
   ${space}
`;

// You can apply typed default props here based on theme
Box.defaultProps = {
   m: 3,
   p: 2
};

// Then you can use typed props elsewhere (totally contrived), obviously
const BoxWithContent = (content: string): any => (
   <Box mr={2} pb={4}>{content}</Box>
);

export default BoxWithContent;
````

This gives all the static typing when composing, as well as when using the theme prop provided inline via something like: 

````js
width: ${props => props.theme.space[4]}px;
````

I'll submit the PR and see what people think, but it seems like it works well to me :)

**Comment by phobon** [comment]
Also, to follow up maybe [this pull in ts2.9](https://github.com/Microsoft/TypeScript/pull/23430) (due this month) would solve some issues, so you could potentially do:

````js
import styled from 'styled-components';
import { width, space, WidthProps, SpaceProps } from 'styled-system';

type BoxProps = WidthProps & SpaceProps;

const Box = styled.div<BoxProps>`
   ${width}
   ${space}
`;
````

If that's how it actually turns out, that would be really great 👍

**Comment by jxnblk** [comment]
Closing (https://github.com/jxnblk/styled-system/pull/181#issuecomment-396086709)
