### ISSUE TITLE
Feature: propTypes support for custom CSS in system-components

### ISSUE THREAD

**Issue by bigslycat** [jxnblk/styled-system#171]
I create the custom CSS like [any style](https://github.com/jxnblk/styled-system#table-of-style-props) of `styled-system` (space, color, etc.) and use in my component:

```js
import { css } from 'styled-components'
import system from 'system-components'
import { bool } from 'prop-types'

const myCSS =  css`
  color: ${props => props.primary && primaryColor};
  color: ${props => props.secondary && secondaryColor};
`

myCSS.propTypes = {
  primary: bool,
  secondary: bool,
}

const Heading1 = system(
  { fontSize: 9, m: 0 },
  myCSS,
  'color',
  'fontSize',
  'space',
)
```

It's nice but incomplete feature. Why? When I use any keys of `styled-system` style, my new component receives `propTypes` properties of this and merges it. Also `system` sets default `blacklist` prop containing all keys of `propTypes`. It perfect! But this does not happens when I uses `myCSS`. And I forsed to cheat:

```js
Heading1.propTypes = {
  ...Heading1.propTypes,
  ...myCSS.propTypes,
}

Heading1.defaultProps = {
  ...Heading1.defaultProps,
  blacklist: Object.keys(Heading1.propTypes),
}
```

My problem is [here](https://github.com/jxnblk/styled-system/blob/f0b9a71a2be63b94ecef685a5b88740423d37bd4/system-components/src/System.js#L32). What about adding support of this case? I can do it if OK.

**Comment by jxnblk** [comment]
I've moved system-components to https://github.com/rebassjs/components so closing this out
