### ISSUE TITLE
Perf with responsive styling and pure components

### ISSUE THREAD

**Issue by adiun** [jxnblk/styled-system#172]
I'm a big fan of styled-system so first, thanks! 

I was curious about the use of the array literal in responsive styling: `<RoundedBox borderRadius={[1,2]} />` I created a little sandbox to show this: a responsive-styled pure component will re-render even though incoming props from the parent component do not change: https://codesandbox.io/s/m7p59mv3xx

The example is kind of contrived - I want the RoundedBox component to be pure so it's pretty obvious this will fail when you pass a prop with an array literal.

Perf should be measured before optimizing - however - given that object/array literals in renders is an infamous way of accidentally re-rendering in React, do you think there should be a note in the docs to mention that using responsive styling through array literals will break pure components? A simple suggestion is, if you're using a pure component, break out the array literal into a const...

**Comment by jxnblk** [comment]
Sorry for the delay, I haven't looking into the performance implications at this level, but I'd guess that it's negligible for most use-cases. Feel free to experiment on a branch with the benchmarks and let me know if you find anything interesting. I think a potential future solution for some of this might be in using babel plugins, but going to close this issue out for now

**Comment by AaronBuxbaum** [comment]
For what it's worth, we found a pretty significant performance impact with inline array literals, in that it effectively ruins `pure`. With a relatively large app, it becomes important to use `pure` to keep performance reasonable, and any prop literal is inherently a reference mismatch -- having a note in there might be valuable to others with larger-scale projects.

Also interested in which Babel plugins you're referring to, as we'd love to utilize them to improve our performance.

**Comment by georgefeast** [comment]
@AaronBuxbaum How did you identify this performance issue? Am trying to figure out a sporadic bug at the moment that I think might be related to performance but don't know how to identify.. any leads much appreciated

**Comment by AaronBuxbaum** [comment]
> @AaronBuxbaum How did you identify this performance issue? Am trying to figure out a sporadic bug at the moment that I think might be related to performance but don't know how to identify.. any leads much appreciated

If you're seeing a lot of renders in your react dev tools, something is updating too much, and this is one possibility. I think your first step should be to figure out if your renders are expensive, or if you're re-rendering too much. Once you're there, you can dig into the problem -- multiple renders implies problems with things like this (which means that you can resolve a lot by hoisting object/function literals and using `pure`), but expensive few renders implies very different problems.
