### ISSUE TITLE
Reduce bundlesize using Rollup

### ISSUE THREAD

**Issue by Geeman201** [jxnblk/styled-system#178]
Hey,

First up thanks for this project! I was thinking of rolling something like this and discovered this while researching pre-existing libraries. It turned out to be exactly what I wanted (and a little bit more) so thanks!

I was looking at the outputted bundle and couldn't help but notice that there's a few optimisations which could be applied to shrink the bundle size (specifically around duplication).

I've experimented with rollup (as this is what I'm familiar with) and looked through the historic issues and came across a short discussion here in [PR 101](https://github.com/jxnblk/styled-system/pull/101#issuecomment-365566718)

I just wanted to reopen that discussion after experimenting with rollup on this project (Happy to PR it in if you'd like).

Perks of using rollup:
**ES module build**
Allows for better tree shaking in downstream projects

**Bundle Visualiser**
Produces a [pretty report on bundle contents](https://www.npmjs.com/package/rollup-plugin-visualizer)

**Uglify & Minify** 
Shrinks bundle size

**Bundle Size**
Finally in my opinion the most valuable:

| Tool  | Uncompressed | gzip |
| ---- | ---- | ---- |
| Babel (Current) | `44 kb` | `7.19 kb` |
| Rollup (with uglify) | `12 kb`  | `3.87 kb` | 
| Rollup (without uglify) | `24 kb`  | `4.9 kb` |

**Comment by jxnblk** [comment]
I think this can be considered resolved since the latest package includes an ES modules version in dist
