### ISSUE TITLE
Responsive on Desktop but not Mobile

### ISSUE THREAD

**Issue by jay-manday** [jxnblk/styled-system#19]
Hi, i've been been noticing something as i've been working with this excellent system. The views are responsive work great but only on a desktop display, not on mobile. When I inspect via dev tools and on my own device I'm only getting the desktop view and not the view associated with corresponding breakpoints. This might totally be a error on my end but i'm not sure how to proceed

Would really appreciate any feedback on how to solve this problem. Thanks again for all this amazing work, these libraries are really useful for spinning up layouts quickly! 

https://jm-site-react-ondibdnarc.now.sh/

https://github.com/jay-manday/jm-site-react

**Comment by jxnblk** [comment]
Are you missing the viewport metatag?

https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag

**Comment by jay-manday** [comment]
ahhhh! works perfectly now. 
thanks!
