### ISSUE TITLE
Extending system component with another system component

### ISSUE THREAD

**Issue by selrond** [jxnblk/styled-system#194]
Is there a way to extend system component with another system component?

For instance, say I have a generic Box component

```js
import system from 'system-components'

const Box = system(
	'space',
	'width',
	'fontSize',
	'textColor',
	'bgColor',
	'color',
)

export default Box
```

and I want to extend it to have - say - Grid prop functions:

```js
import system from 'system-components'

const Grid = system(
	// I want to inherit these from Box component:
	// 'space',
	// 'width',
	// 'fontSize',
	// 'textColor',
	// 'bgColor',
	// 'color',

	'gridGap',
	'gridColumnGap',
	'gridRowGap',
	'gridColumn',
	'gridRow',
	'gridAutoFlow',
	'gridAutoColumns',
	'gridAutoRows',
	'gridTemplateColumns',
	'gridTemplateRows',
)

export default Grid
```

I know I can use `styled-components`' `.extend` method, but the I lose implicit prop blacklisting functionality. 

Is there an elegant way to achieve that?

**Comment by jxnblk** [comment]
The `is` prop *should* work for what you're describing, e.g. `const Grid = system({ is: Box })`

**Comment by selrond** [comment]
@jxnblk how did I not think about that... Thank you! Works lika a charm
