### ISSUE TITLE
textDecoration and textTransform

### ISSUE THREAD

**Issue by benjamingeorge** [jxnblk/styled-system#195]
How come these two basic css props are not supported for either styled-system or system-components?  How do I use them and make sure they React doesn't add them to the actual DOM node as an attribute?

**Comment by jxnblk** [comment]
In my opinion, there aren't enough possible values with these properties to justify creating theme values for them. That said, you can create your own style functions if you want something like that, see https://github.com/jxnblk/styled-system/blob/master/docs/api.md#style

If you're using system-components, you can pass custom functions or style objects as the second (or higher) argument and it should work

**Comment by aliankarali** [comment]
First of all great job with this library, I love it, @jxnblk, but I don't get your argument. They should be part of the core API. Ultimately, I am trying not to use styled components outside of the design system library so I have some cases for example there is this text type where text should be capital. Other than that, I create my own generic components and pass styles as props when I want to styled them, so I am trying to use styled-system most of the cases. So as @benjamingeorge said, these are basic props, please reconsider your evaluation.
