### ISSUE TITLE
Question:  Adding a parameter to a "nested" element in a styled component.

### ISSUE THREAD

**Issue by kimfucious** [jxnblk/styled-system#197]
Hi there,

Is it possible do this?  Or is the a better way of approaching this?

My initial thought was to not have to create custom components for `h1`, for example, letting the styled component handle the high-level "generic" styling at the component level, and then use a styled system utility to control the fonts (leveraging the default breakpoints) at a more granular level on the render side.

I'm intentionally omitting using a theme in the example below for simplicity, as I don't think it would help in this situation (though I could certainly be wrong about that).

## Here's what I'm trying to do

1.  Create a styled component using Object Styles to nest elements (e.g. `h1`).
2.  Add fontSize to the styled component

```js
import styled from "react-emotion";
import { fontSize } from "styled-system";

const Hero = styled.div(fontSize, { // <= Add fontSize here
  alignItems: "center",
  display: "flex",
  flexDirection: "column",
  height: "100vh",
  justifyContent: "center",
  textAlign: "center",
  overflow: "scroll",
  h1: {
    color: "white",
    letterSpacing: "2px",
    textShadow: "2px 2px black",
    textTransform: "uppercase",
  },
  h3: {
    color: "white",
    fontWeight: "100",
    textShadow: "2px 2px black",
  },
});

export default Hero;
```

3.  Render the component, but use `fontSize` on a nested element instead of, or in addition to the component

```jsx
<Hero>  // <-- no parameter here
  <h1 fontSize{[2,2,3]}>Fancy Title</h1> // <-- but here
  <h3>I'm a fancy tagline. Ain't I fancy!</h3>
</Hero>

**Comment by jxnblk** [comment]
As far as how styled-components works, you'll only ever be able to get props from the component you're creating – in this case the Hero. There are ways to target the `h1` element from the Hero definition, but it can't really check its child elements' props without parsing `props.children` – e.g. you'll probably want to make use of `React.Children` for this sort of thing. That said, in the example you give, I think you'd be better off creating a styled component for the `h1` element

**Comment by kimfucious** [comment]
Thanks @jxnblk for the follow up.

I came to the realization that I was trying to do too much with with a single `Hero` component, and I wound up breaking it down into smaller components, including a styled.h1 as you suggested.

```js
import styled from "react-emotion";
import { fontSize, space } from "styled-system";

export default styled.h1`
  ${fontSize};
  ${space};
  grid-area: title;
  font-family: "Russo One", sans-serif;
  letter-spacing: 1px;
  text-align: center;
  text-shadow: 2px 2px black;
  text-transform: uppercase;
`;
```

While I was initially that thinking this was more work than desired up front, once done, building out pages is a lot quicker, as it's more assembling the components.  And styled-system awesome for styling those components! :smile:

```html
<Title fontSize={[5, 6, 6, 7]} mb={[0, 3]} mt={["-2em", "-2em"]}>
  Styled Title
</Title>
```
