### ISSUE TITLE
[Error] getting `TypeError: Cannot convert undefined or null to object`

### ISSUE THREAD

**Issue by selrond** [jxnblk/styled-system#199]
![image](https://user-images.githubusercontent.com/6603389/41218840-c4d80054-6d5c-11e8-999f-a6b64764da26.png)

After updating, I'm getting a TypeError. 

![image](https://user-images.githubusercontent.com/6603389/41218999-46b479cc-6d5d-11e8-997b-62893c2936d4.png)

Stack trace is quite unclear, but it's most probable to have something with #196

**Comment by selrond** [comment]
Narrowed it down a bit more - commenting out 'size' prop function gets rid of the error:

```js
import system from 'system-components'

const Box = system(
  'space',
  'width',
  'fontSize',
  'color',
  // 'size',
)
```

**Comment by allforabit** [comment]
I've added another pull request to fix this issue. To test the new version could you paste the following into `node_modules/styled-system/dist/styles.js` in place of the existing `size` function:
```
var size = exports.size = function size(props) {
  return (0, _util.merge)(sizeHeight(props) || {}, sizeWidth(props) || {});
};
```
I've added a default empty object to avoid the `null` error that you reported.
