### ISSUE TITLE
Using styled-system with SSR frameworks like Next.js

### ISSUE THREAD

**Issue by callumflack** [jxnblk/styled-system#20]
When using styled-system via styled-components within Next.js (or Nuxt.js), which have server-side rendering by default, the css styling of NPMs (such as styled-system) isn't applied.

Is there a method to easily enable this?

**Comment by jxnblk** [comment]
This is a pretty good example of how to set up SSR with next.js and styled-components. https://github.com/zeit/next.js/tree/v3-beta/examples/with-styled-components

Since your issue is more related to those libraries, closing this for now

**Comment by callumflack** [comment]
Thanks @jxnblk I'll go back to the fundamentals

**Comment by claytn** [comment]
^ The link above was broken. This is the updated one: https://github.com/zeit/next.js/tree/canary/examples/with-styled-components
