### ISSUE TITLE
System Components depends on styled-components directly

### ISSUE THREAD

**Issue by bebraw** [jxnblk/styled-system#201]
The direct dependency is problematic as if you are using npm 5, it will pull the dependency inside System Components package instead of reusing possible project-wide dependency. This can lead to multiple instances of styled-components running.

Likely the easiest way to fix this would be to turn styled-components into a peer dependency of System Components and let the user decide which version of styled-components to use. In order to work around the issue, I went with a webpack alias for now.

**Comment by jxnblk** [comment]
I *think* this should be resolved now, but please reopen if not
