### ISSUE TITLE
Use object instead of array for space key in theme

### ISSUE THREAD

**Issue by frontendmonster** [jxnblk/styled-system#205]
Using arrays and indexes will end up with [magic numbers](https://en.wikipedia.org/wiki/Magic_number_%28programming%29) in the source code.

all the code like ```<Box p={3} />``` gonna say is that someone uses the fourth element in space object as a padding for Box and nothing more. it would be hard to determine should I use 2 or 3 while contributing as a team.

I know it can be defined as a new custom responsive style but why it's not a default behaviour (it will work fine for arrays too)

## Example
```javascript
  theme={
    //...
   space={
      sm: 0,
      md: 16,
      lg: 32,
   }
}

<Box p="sm" />
```

**Comment by jxnblk** [comment]
I wouldn’t consider them magic numbers at all, just steps on a scale. The teams I’ve worked with don’t seem to have any issue working with scales, but the example you’ve given will work if that’s what you prefer
