### ISSUE TITLE
Changing background color on a pseudo class

### ISSUE THREAD

**Issue by jsonmaur** [jxnblk/styled-system#215]
This one tripped me up, so it might be good to be more specific about it in the documentation (or it could be a bug, not sure.) But you should be able to pass through any styled-system prop to a pseudo-class prop, correct?

I was trying to change the background color of an element when hovering (getting the color from the theme), and thought `bg` would be valid according to what I was able to find in the docs. But that does not work, you have to use `backgroundColor` instead:

```jsx
// does not work
<Box
  hover={{
    bg: 'gray'
  }}
/>

// works
<Box
  hover={{
    backgroundColor: 'gray'
  }}
/>
```

**Comment by jxnblk** [comment]
The latest version removes the pseudoclass utilities, and I’d suggest handling these on your own if it’s something you’re making heavy use of
