### ISSUE TITLE
themeGet only returns strings?

### ISSUE THREAD

**Issue by andyford** [jxnblk/styled-system#225]
In my theme I have:

```
    myComponent: {
        cellWidth: 30,
        padding: 5,
    },
```

When I do something like `${themeGet('myComponent.cellWidth') * 2 }px`, the compiled css is `NaNpx`

Is this a known issue?

**Comment by jxnblk** [comment]
The `themeGet` utility should return a number if that's how it's defined in the theme, but there's a small issue with the code example above, the function signature is `themeGet(paths)(props)`, so you'd need `${props => themeGet('myComponent.cellWidth')(props) * 2}px`
