### ISSUE TITLE
Proposed renaming of packages.

### ISSUE THREAD

**Issue by DylanVann** [jxnblk/styled-system#227]
The hardest thing in computer programming. 

**Current:**

- `styled-system`
- `grid-styled`
- `system-components`

I find I get confused thinking about which package what I want is from or when I'm trying to search for docs.

**Proposal:**

- `@styled-system/core`
- `@styled-system/grid`
- `@styled-system/components`

For convenience `styled-system` could just wrap up all the packages even if they're developed in isolation. If ES modules are used then for people using ES module aware bundlers it will be more convenient and won't affect bundle size.

If I'm trying to search for stuff related to the grid I want to just type "styled system grid" or "styled system components".

I'd be willing to do a PR if you want this change made.

**Comment by jxnblk** [comment]
I've been considering this, but I'm not sure how much renaming things would actually make things simpler. The three packages you mentioned would generally not be used in the same module or for the same purpose.

As for actually renaming the packages, It'd require a bit of effort, but I'm currently leaning towards using the `@rebass` namespace, e.g. `@rebass/grid` `@rebass/system` `@rebass/components` etc

**Comment by DylanVann** [comment]
I think there would probably be a reasonable amount of people using all three modules.

I guess `system-components` is a higher level API for `styled-system`, but if I'm using `system-components` I frequently have to refer to the `styled-system` documentation. I do understand that with regards to software architecture they're separate, but I think from a user perspective it's sort of like they're one project (all part of one grand vision ✨).

I think the `@rebass` namespace would be good too, in fact I think maybe I should just be using Rebass instead of using these modules directly, which would solve my issues.

**Comment by jxnblk** [comment]
I've started working on reorganizing the modules a bit. So far there is now `@rebass/components` and `@rebass/grid`, and I'll be following with a a new version of Rebass after. This library will continue to be `styled-system` for the time being so closing this out.

- https://github.com/rebassjs/components
- https://github.com/rebassjs/grid
