### ISSUE TITLE
Print Styles

### ISSUE THREAD

**Issue by johnpolacek** [jxnblk/styled-system#228]
How would you recommend handling print styles with Styled System?

**Comment by jxnblk** [comment]
Don't know that I've really tried to figure that out specifically for styled-system. Each breakpoint uses the `screen` media query, which shouldn't affect print styles. If I were to add print styles to a component, I'd probably hard-code it in the definition...

**Comment by avidrucker** [comment]
I'd love to figure out a workflow for this as well. Perhaps we can connect/collab on this @johnpolacek ?

**Comment by johnpolacek** [comment]
The main use case is to simply hide the element when printing. I don't think this is something that styled system needs to handle necessarily (I myself am a fan of playing the "out of scope" card). 

@avidrucker For my little side project (a trip planner), I have some global styles so for now I made a utility class - `className="hidePrint"` - which works fine. 

In a perfect world, something like `print={{display:none}}` would work pretty nicely.

**Comment by avidrucker** [comment]
I'm all about less is more myself. That said, I'd find it interesting/fun to make a Tachyons component/utility library add-on that offers multiple print options (hiding images or certain elements by certain criteria (user-designated, programatically/dynamically, etc.)), dimming/lightening images, etc..

**Comment by jxnblk** [comment]
I'm going to close this issue out in the hopes that other libraries can pick up the baton on this idea. Good luck!

**Comment by sidhuko** [comment]
Interested to know whether anyone released anything related to styled-system print solution?
