### ISSUE TITLE
system-components and responsiveStyle

### ISSUE THREAD

**Issue by vesparny** [jxnblk/styled-system#231]
what's the recommended way to create [responsive styles](https://github.com/jxnblk/styled-system/blob/master/docs/api.md#responsivestyle) using system-components ?

**Comment by jxnblk** [comment]
You can pass any style function as an argument to system-components, e.g.

```js
import system from 'system-components'
import { responsiveStyle } from 'styled-system'
const myStyleFunction = responsiveStyle({ prop: 'opacity' })
const Box = system({}, myStyleFunction)
```

**Comment by webattitude** [comment]
how to achieve this now, since responsiveStyle has been removed ...?
