### ISSUE TITLE
Usage of style objects for complexStyle/variant

### ISSUE THREAD

**Issue by colepeters** [jxnblk/styled-system#233]
Wrote this up while reviewing #232.
It may be tangentially related to #116.

I'm still using v1 of Styled-system for my day to day work, so the concept of `complexStyle` (now `variant`) was new to me. Having reviewed it, I'm curious as to the usage of style objects as the API for creating variant styles.

In one sense I can see the appeal (if my primary/secondary buttons, for example, are defined in my theme, I can easily white label my UI by dropping in a different theme with different values), but on the other hand defining styles this way feels like it loses something — especially since I can't refer to my theme's properties in my style object, since they're part of the same object (nor can I utilize styling props from Styled-system):

```js
const theme = {
  colors: {
    one: '#f00',
    two: '#00f'
  },
  space: [0, 8, 16, 32, 64…],
  buttons: {
    primary: {
      color: 'white',
      backgroundColor: one,  // 🚨nope!
      px: 2,  // Can't do this…
      py: 1, // …or this either
    }
  }
}
```

_(I suppose you could, in this example, define your colours externally to `theme` and simply assign them to your theme's `color` properties and your complex styles to get around this, but then you're still not actually referring to your_ theme _in your complex styles.)_

For comparison (and maybe to explain why I'm finding this odd), I've been setting up component variants something like this:

```js
// Super quick and dirty example button with variants

import { space } from 'styled-system'

const primaryButtonStyle = `
  color: ${props => props.theme.colors.mayonaise};
  background-color: ${props => props.theme.colors.ketchup};
  padding: ${props => props.p || props.theme.space[4]};
`

const secondaryButtonStyle = `
  color: ${props => props.theme.colors.mustard};
  background-color: ${props => props.theme.colors.charcoal};
  padding: ${props => props.p || props.theme.space[2]};
`

const Button = styled.button`
  // core styles, blah blah…
  ${space}
  ${props => props.primary && primaryButtonStyle}
  ${props => props.secondary && primaryButtonStyle}
`
```

This allows me to do component variants while styling them using values defined in my theme (plus being able to use things like media queries which I can't do in a style object).

I admit that I'm limited by my own experience and use cases (and my use case above may be biased by using Styled Components). I'm just wondering if the use of style objects isn't fairly limiting for a utility that might otherwise be extremely powerful — or, alternatively, if perhaps I'm being ignorant of a utility that is already extremely powerful. Or maybe it's just an option that's being provided, and if it doesn't do what I need it to, I should just stop whining already! 😉 

I'm also aware that using style objects might be the only CSS-in-JS agnostic solution available, or that some other technical limitation that I'm not aware of might make style objects the only feasible way to make this utility work.

(I'm sorry if this isn't exactly a pointed question; please let me know if none of this rambling makes sense!)

**Comment by joltmode** [comment]
Yeah, I also stumbled upon this, with v3.

**theme.js**
```
export default {
  fonts: {
    sans: '"GT Walsheim", Helvetica, sans-serif',
  },
  fontWeights: {
    light: 300,
    medium: 500,
    bold: 700,
  },
  textStyles: {
    label: {
      textTransform: 'uppercase',
      fontSize: [12, 14],
      lineHeight: [1, 19 / 14],
      fontWeight: 'light'
    },
  },
}
```

**Text.js**
```
import styled from 'react-emotion''
import { textStyles } from 'styled-system'

const Text = styled('p')`
  ${textStyles}
`

Text.propTypes = {
  ...textStyles.propTypes
}

export default Text
```

Now, looking to use it like:
```
import Text from './Text'

export default () => (<Text textStyle="label">Label</Text>)
```

I was expecting to get responsive font sizes, line heights, font weight being resolved from other theme properties and text transform being set.

In reality, it's only `text-transform` and `font-weight` that are being set. I assume, because they're strings. But from those two, `fontWeight` is set as is - `light`, not getting resolved to `300`:
```
.css-rexalj {
    text-transform: uppercase;
    font-weight: light;
}
```

Expected result (for example):
```
.css-rexalj {
    text-transform: uppercase;
    font-weight: 300;
    font-size: 12px;
    line-height: 1;
}

@media screen and (min-width: 40em) {
    .css-rexalj {
        font-size: 14px;
        line-height: 1.357;
    }
}
```

Otherwise, variants feel totally underpowered and inconsistent.

@jxnblk it's been some time since initial issue, what is your view on this?

**Comment by jxnblk** [comment]
@joltmode To not overload/conflate the props and style objects (which are different), the variants only accept style objects (not styled-system props). If you want to mix the two, use the [`mixed`](https://github.com/jxnblk/styled-system/blob/master/docs/api.md#mixed) utility.

I'm keeping this issue open for discussion for the time being

**Comment by joltmode** [comment]
Hmm, how would I go about mixing them to get to my scenario?

**Comment by jxnblk** [comment]
Going to close this out since I think conflating props and style objects with the `variant` utility is probably more complex and potentially confusing than what this library seeks to do
