### ISSUE TITLE
Define component styles without exposing them to props

### ISSUE THREAD

**Issue by sapegin** [jxnblk/styled-system#234]
I’d like to define component styles like this (for example):

```js
const Card = system(
    {
        px: 5,
        py: 3,
        borderWidth: 1,
        borderColor: 'primary',
        borderRadius: 'base',
    }
);
```

But don’t want users to be able to do:

```html
<Card borderColor="red" />
```

If we add some kind of a props filter, so you could do:

```js
const Card = system({
  borderColor: 'lightGray'
}, props => ({
  borderColor: props.variation === 'primary' ? 'primary' : 'lightGray'
}))
```

That would make styled-system / system-components two times more useful in my opinion.

I may have missed something and there is a way to do that already. If not, I'd like to try to implement that if you like the API (or have better ideas). What do you think?

**Comment by jxnblk** [comment]
I'm not sure why you'd want this exactly, but the `themeGet` utility can be used to set styles based on the theme, that aren't props.

```js
import { themeGet } from 'styled-system'
import styled from 'styled-components'

const Box = styled.div`
  borderRadius: ${themeGet('radii.base')};
`
```

**Comment by sapegin** [comment]
Because writing something like `{px: 5, px: 3}` is much nicer than `padding-left: ${themeGet('...`, but leaking these props will give the user too much flexibility: not every detail of the component should be configurable by the user, and rarely props like `borderColor` make good API.

**Comment by jxnblk** [comment]
> Because writing something like {px: 5, px: 3} is much nicer...

Personally, I don't think mixing the ideas of style props and style functions in this case is a good idea. Styled System is meant for when you want to define props. If it's just static styles, I'd recommend handling them like my example above

**Comment by jxnblk** [comment]
That said, a separate wrapper could be built to do what you're suggesting. If you wanted to use styled-system, each function returns an object, which could be used in a component definition if you wanted to. E.g. 

```js
const Box = styled.div`
  ${borderRadius({ theme, borderRadius: 'radii.base' })}
`
```

**Comment by sapegin** [comment]
> Personally, I don't think mixing the ideas of style props and style functions in this case is a good idea. 

Good point! Though the API would be too good to not want to use it ;-)

You last example would be a bit more complex, because we need to pass theme from props (or I’m missing some magic here:

```js
const Box = styled.div`
  ${({ theme }) => borderRadius({ theme, borderRadius: 'radii.base' })}
`
```

**Comment by sapegin** [comment]
I think the new `css` is exactly what I wanted:

```js
import { themeGet, css } from 'styled-system';
const Input = styled.input`
	${props =>
		css({
			theme: props.theme,
			p: 2,
			fontFamily: 'base',
			fontSize: 'base',
			color: 'base',
			bg: 'bg',
			borderColor: 'primary',
			borderRadius: 'base',
		})};

	box-sizing: border-box;
	display: block;
	width: 100%;
	border-width: 1px;
	border-style: solid;

	&:focus {
		outline: 0;
		box-shadow: 0 0 0 2px ${themeGet('colors.focus')};
	}
`;
```

Thank you! 🎆

**Comment by jxnblk** [comment]
Heads up, I meant to rename that before merging, but the function is now called `mixed`

**Comment by bradley** [comment]
Did the API change since this comment? `mixed` doesnt seem to exist, and I cant really find any documentation of how to do this either.

My particular problem case is that I have a component on which Id like to have a border width that comes from my theme's `borders` object. 

If borders look like this:
```
const borders = [
  0,
  "1px solid",
  "2px solid",
  "4px solid",
  "8px solid",
  "16px solid",
  "32px solid",
];
```

I can set the border on my styled component using:

```
const myComponent = styled.div`
  ${ borders }
`;

myComponent.defaultProps = {
  border: 2
};
```

But how would I do this if I dont wish to expose border settings as props on the component? Maybe its the opinion `styled-system` that doing this kind of thing is outside the scope of the library, but I cant seem to determine what the suggested alternative route is that still uses my theme. The following solution doesnt seem to be appropriate either (or is it?):

```
const myComponent = styled.div`
  border: ${ ({ theme: { borders } }) => borders[2]};
`;
```
