### ISSUE TITLE
vertical-align not exposed

### ISSUE THREAD

**Issue by Kikobeats** [jxnblk/styled-system#237]
Hello,

I'm trying to use `verticalAlign` but it throws an undfined error

```jsx
import styled from 'styled-components'

const Box = styled(BoxBase)`
  ${textAlign};
`
```

console says:

```
{ TypeError: Cannot read property 'propTypes' of undefined
```

Checking the PR related with vertical-align (https://github.com/jxnblk/styled-system/pull/213) it looks like only `style` path is exported 🤔

**Comment by jxnblk** [comment]
Thanks! Yeah, it looks like it’ll need to be exported from `src/index.js`
