### ISSUE TITLE
background-image with gradient

### ISSUE THREAD

**Issue by Kikobeats** [jxnblk/styled-system#238]
Because the current `background-image` is wrapping the value provided as url:

https://github.com/jxnblk/styled-system/blob/9add1edd4d5855aecc2a1dabb7aa6bdda67e0bbb/src/styles.js#L320

it is not possible combine it with a gradient, like:

```jsx
backgroundImage='linear-gradient(rgba(0, 0, 255, 0.5), rgba(255, 255, 0, 0.5)), url("/static/img/hero/3.jpeg")'>
```

**Comment by jxnblk** [comment]
Thanks! Yeah, I've thought about this a little bit, but maybe with #232 it'd be good to remove that default value transform. I've also thought that it could be helpful to have a `gradient` style helper specifically for gradients

**Comment by jxnblk** [comment]
With v3, `backgroundImage` no longer adds the url syntax
