### ISSUE TITLE
Max-width not working

### ISSUE THREAD

**Issue by developer239** [jxnblk/styled-system#253]
```
<Flex>
  <Box maxWidth={600}>
    Some text
  </Box>
</Flex>
```

generates something like this:

![screen shot 2018-07-24 at 12 13 49](https://user-images.githubusercontent.com/14946081/43132141-19a8a124-8f3b-11e8-9ddb-c57489f3b316.png)

which will not prevent children from expanding over 600 pixels in width.

**Comment by jxnblk** [comment]
Did you add the `maxWidth` function to your definition for Box? That prop is not included in grid-styled fwiw

**Comment by developer239** [comment]
I wanted to use [rebass](https://github.com/jxnblk/rebass) but then I decided to write my own components because it just seemed like an overkill to use UI library with many dependencies when I have to extend every component anyway.
