### ISSUE TITLE
Add flexbox and cssgrid functions?

### ISSUE THREAD

**Issue by flybayer** [jxnblk/styled-system#256]
Like with `space`, I'd love to be able to add all flexbox props to a component with one line such as `flexbox`. 

Same for CSS grid with something like `cssGrid`.

I'm happy to make a PR but want to make sure you are open to this first.

**Comment by dmackerman** [comment]
Was writing a component today and wished I had the CSS Grid shorthand without having to use `css` (which isn't bad in itself).

**Comment by jxnblk** [comment]
Planning on merging #255 soon

**Comment by flybayer** [comment]
@jxnblk cool, that would work, but I still have to go to the effort of doing that, importing the composed flexbox function to every component I need it versus just adding `'flexbox'` as a string like `'space'`.

**Comment by jxnblk** [comment]
You can use `compose` to build your own utils, right? That's currently how `color` works: https://github.com/jxnblk/styled-system/blob/master/src/styles.js#L46-L49 – going to close this out, but also sounds like what you're talking about might be related to system-components, if so, I've move that to a new repo here: https://github.com/rebassjs/components
