### ISSUE TITLE
Question: How to extend react components in system-component@3.0.0?

### ISSUE THREAD

**Issue by frontendmonster** [jxnblk/styled-system#265]
Hi, I have a question.
with `system-components@2.2.2` and I had a Link system component that extends from `react-router` NavLink and it was working as expected.

```javascript
const Link = system({
  is: NavLink
  }
  //...
);
```

then, I upgrade `system-components` to v3.0.0 and now I'm getting a `Warning: Received a 'function' for a string attribute 'is'. If this is expected, cast the value to a string.` error and it stops working as Link component.

is this bug or we should just use HTML tag as `is` prop?

**Comment by jxnblk** [comment]
That sounds like a bug, if React is passing the `is` prop as an attribute – is that the complete code example to reproduce? You might want to try a clean install to ensure all the latest packages have been updated

**Comment by frontendmonster** [comment]
I dig into the code and find out the problem came from the #248 issue. 
it gets fixed by adding breakpoints' units.

But I still get the prop-types error, here is a rendered Link

```html
<a 
  class="sc-chPdSV ibDsUs"
  height="100%" 
  blacklist="css,m,mt,mr,mb,ml,mx,my,p,pt,pr,pb,pl,px,py,width,color,bg,fontSize,fontFamily,letterSpacing,border,borderTop,borderRight,borderBottom,borderLeft,borderColor,borderRadius,display,maxWidth,minWidth,height,maxHeight,minHeight,alignItems,alignContent,justifyContent,flexWrap,flexDirection,flex,flexBasis,justifySelf,alignSelf,order,position,zIndex,top,right,bottom,left,boxShadow" 
  href="/">
</a>
```

**Comment by jxnblk** [comment]
I've moved system-components to a new repo https://github.com/rebassjs/components – if you're still seeing issues, please open a new issue there
