### ISSUE TITLE
Example/docs about how to combine variant with mixed

### ISSUE THREAD

**Issue by joltmode** [jxnblk/styled-system#266]
I find it hard to understand how `mixed` and `variant` are meant to be combined.

[Docs mention such possibility](https://github.com/jxnblk/styled-system/blob/master/docs/api.md#mixed), but I don't get it:
> This can be used in combination with the `variant` utility or directly in component definitions. This utility will not add any props to a component.

Maybe docs should be extended with examples and use cases?

---

I see it could be used in `theme` definition, but I have to pass `theme` to `mixed`, which removes the dynamic aspect of styles:

```js
const theme = {
  fontSizes: [
    12,
    18,
    24
  ],
  colors: {
    red: 'maroon'
  },
  textStyles: {
    label: mixed({
      /* I need to get theme in here... */
      fontSize: [0, null, 1],
      color: 'red',
      fontWeight: 'bold',
      textTransform: 'uppercase'
    })
  }
}
```

Because the only way I see it's doable is to separate the sections...
```js
const theme = { 
  /**/ 
  textStyles: {} 
}

theme.textStyles.label = mixed({ theme, /**/ })
```

Checking through `variant` source, I don't see how I would integrate `mixed` there either.

---

What do the docs refer to then?

**Comment by jxnblk** [comment]
I wouldn't recommend using `mixed` at all at this point. It was added due to feedback, but I am starting to think it's confusing and a little antithetical to this library
