### ISSUE TITLE
Not an issue but a kudos....

### ISSUE THREAD

**Issue by zentuit** [jxnblk/styled-system#27]
`styled-system`, and specifically `responsiveStyle`, has made a significant change to how I write my styled components. The more I use it, the more I see my components styling changing and becoming more clean.

Excellent job and my thanks for this package!

**Comment by jole78** [comment]
Couldn't agree more. The way I write styled components with styled-system has fundamentally changed the size and structure of our code base. Now we basically have like a base component that handles all sizing and other stuff and all other special components just compose that one and adds their specific stuff. That way when we use the we can always control padding and margins via p={1} my={2} etc if we need to. 

So a big kudos!

**Comment by jxnblk** [comment]
Thanks! Glad this is working out for you and your teams! 😎
