### ISSUE TITLE
Applying multiple variants

### ISSUE THREAD

**Issue by browniefed** [jxnblk/styled-system#272]
After the deprecation of boolean props (I asked here and realized https://github.com/jxnblk/styled-system/issues/271 ) it doesn't seem like you can apply multiple of the same variant now.

For example I'd frequently define `textStyles` with `fontFamily`, uppercasing, bolding etc. Then for a component I could just apply `<Text sourceSans bold caps>My Text</Text>` this doesn't appear to be possibly anymore.

**Comment by andrewthauer** [comment]
If you can choose between any combination would that not bypass the design constraints for the design system? I would imagine the intention was to enforce `textStyles` (and other variants) to be clearly defined and predictable.

However, that said, I can see this sort of thing being useful when you have different variant type combinations (e.g. buttons - primary/secondary, normal/outlined, sm/md/lg).

You could work around this by having custom variants function/props pointing to the `textStyle` key if you really wanted to accomplish something similar. Or just use boolean props directly encapsulated in a custom style function.

**Comment by browniefed** [comment]
Yeah, previous it accepted an array of textStyles to apply, and or boolean properties and has since been dropped to a single string which was just surprising.

Most of it was just attempting to define custom props that would work with an arbitrary constructed system component. I'll close this issue since it can be all technically solved in user land.
