### ISSUE TITLE
Flex passes down justifyContent, alignItems, etc. to underlying DOM Element in IE11

### ISSUE THREAD

**Issue by formatlos** [jxnblk/styled-system#273]
When using 

```
<Flex justifyContent="center"/> 
```
the `justifyContent` attribute will be passed down to the underlying DOM Element in IE11. 

It's not really an issue with the code of `styled-system` or `system-components` but I still wanted to add an issue if other devs stumble upon that. 

The root cause is the array helper `unique` in `system-components`:
```
const unique = arr => [...new Set(arr)]
```
when transpiling with babel the spread internally uses `Array.from` ending up in 

```
Array.from(new Set(['justifyContent'])) 
```

IE11 doesn't support `Array.from` natively. I were using [polyfill.io](https://polyfill.io/) to automatically polyfill missing language features. As it seems the polyfill is buggy and returns `[]` instead of `['justifyContent']` on IE11 (same with the polyfill listed on [mozilla.org](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from#Polyfill) and possibly others as well, core-js seems to be fine though).

I've filled a bug-report for polyfill.io https://github.com/Financial-Times/polyfill-service/issues/1753, but as other might also be problematic, it's also worth thinking about re-writing the `unique` method. 
I can create a PR if you are willing to do so.

**Comment by formatlos** [comment]
could you please also publish a new npm version

**Comment by jxnblk** [comment]
Should be in `v3.0.1`
