### ISSUE TITLE
system-components emotion babel macros 

### ISSUE THREAD

**Issue by bogdansoare** [jxnblk/styled-system#275]
does system-components support usage of emotion with babel macros https://emotion.sh/docs/babel-plugin-emotion#babel-macros ?

**Comment by bogdansoare** [comment]
using emotion macros requires no setup, you just import from `emotion/macro` instead of `emotion`

**Comment by jxnblk** [comment]
This is just a convenience for you to use in your own application right? I don't think this library has anything to do with `emotion/macro` unless I'm missing something
