### ISSUE TITLE
style() function doesn't use default space

### ISSUE THREAD

**Issue by sapegin** [jxnblk/styled-system#277]
All props defined with `style()` function, like `gridGap`, won't use the [default scale](https://github.com/jxnblk/styled-system/blob/aee03959b98022ff7bd41be74ceff36ecae26784/src/space.js#L53-L55).

I'm not sure that `style()` function should do it, but at least props like like `gridGap` should use it for consistency with other props like `m` or `p`.

I'm happy to submit a pull request for that.

**Comment by jxnblk** [comment]
Yeah, I think this *could* make sense. Should be a fairly straight forward PR unless if you wanna take a stab at it
