### ISSUE TITLE
style props are passed as dom element attributes

### ISSUE THREAD

**Issue by AlahmadiQ8** [jxnblk/styled-system#280]
First, thank you for the awesome project. This really boosted my prototyping workflow with responsive designs.

***Update:** Turned out this isn't related to this library but rather emotion js itself. see https://github.com/emotion-js/emotion/issues/183*

~I'm not sure the the behavior is per design or a bug.~

## ~Issue~

~When I pass props for styling a component, they also get passed to the dom as attributes. Here is an example.~

## Steps to reproduce

Here is a [codesandbox demo](https://codesandbox.io/s/x2zn2yknp4)

```javascript
const Text = styled("div")`
  ${space}
  ${fontSize}
  ${fontWeight}
  ${lineHeight}
  ${color}
`;

const App = () => (
  <div>
    <Text fontSize={[4, 5, 6]} fontWeight="bold" id="Text">
      Emotion demo
    </Text>
  </div>
);

ReactDOM.render(<App />, document.getElementById('root'))
```

![screen shot 2018-09-05 at 9 42 23 pm](https://user-images.githubusercontent.com/3461501/45135728-d04f6200-b155-11e8-9e37-c38f673c6629.png)

## Actual Results 

The renderd element looks like this 

```javascript 
<div font-size="4,5,6" font-weight="bold" id="Text" class="css-qk8np1">Emotion demo</div>
```

## Expected Reaults 

```javascript 
<div id="Text" class="css-qk8np1">Emotion demo</div>
```

**Comment by AlahmadiQ8** [comment]
this issue can be closed. 

I created another issue https://github.com/emotion-js/emotion/issues/838

**Comment by jxnblk** [comment]
Thanks! Yeah this is an issue with how the HOCs in libraries like emotion work. See https://github.com/jxnblk/styled-system/blob/master/clean-tag/README.md
