### ISSUE TITLE
CSS ordering issue

### ISSUE THREAD

**Issue by youngboy** [jxnblk/styled-system#291]
These style props are great, but is it possible to override styles with higher specificity?

For example, in styled-component case

```jsx
const Div = styled("div")(color);
const Block = styled(Div)({ color: "red" });

const app = () => 
    <div>
        <Block>should be red</Block>
        <Block color="green">while it is rendered in red</Block>
    </div>
```

see https://codesandbox.io/s/kk8qopp08v

Or maybe this pattern is discouraged?

Thanks in advance

**Comment by youngboy** [comment]
Updated, add `!important` is work for this case 😂, it would be nice to have an option setting this prop to important by default

```
<Block color="green !important">text in green</Block>
```

**Comment by jxnblk** [comment]
You can set defaultProps for your first example. I wouldn’t recommend introducing specificity if you can avoid it
