### ISSUE TITLE
Is there a way to access the theme from the css prop?

### ISSUE THREAD

**Issue by aaronmcadam** [jxnblk/styled-system#299]
Hi there,

I'm trying to add some custom css to a component, but I'd like to access my themes colours.

e.g:

```jsx
const theme = {
  colors: {
    platform: {
      shades: {
        200: '#e2e4e6',
      },
    },
  },
};

<ThemeProvider theme={theme}>
  <Box
    as="thead"
    borderBottom="2px solid"
    borderColor="platform.shades.200"
    css={`
      border-bottom: 2px solid;
      border-color: platform.blue.500;
    `}
  >
    Content
  </Box>
</ThemeProvider>;
```

**Comment by TrySound** [comment]
Yes, use `ThemeConsumer` or `withTheme` hoc of styled-components or similar of emotion.

**Comment by aaronmcadam** [comment]
Thanks @TrySoun, but my question was really about how to interpolate the theme colour inside my `css` prop string.

**Comment by aaronmcadam** [comment]
Really I'm looking for a function like `themeGet`, but that isn't expecting a default value.

**Comment by jxnblk** [comment]
The `css` prop isn't part of styled-system's core API, but for Rebass, etc. The `css` prop is either a string or object, *not* a tagged template literal, but as suggested above, you can use the `withTheme` HOC to expose `theme` in props
