### ISSUE TITLE
Consider allowing widths to use the same scale as margins

### ISSUE THREAD

**Issue by lucastobrazil** [jxnblk/styled-system#300]
With margins, I can say:
```
<Box m={2} /> 
```

Which, if in my theme I have `space: [4, 8, 16, 32]` then the margin set above is `8px`.

I would like to be able to say:
```
<Box width={2} height={2} /> // 8x8 box
```

I was wondering if there was a reason why we couldn't plug into the `space` values for these properties? Based on the docs it seems that width and height can take percentages, pixel values and responsive width values, but not `space` values.

Perhaps something to consider if you already haven't? In this example, I'm wanting to create some pagination 'dots' that are based on my main 8px scale. The only way I can get them to be 8px is if i say 

```
<PaginationDot width={8} height={8} />
```
but what if the user wanted to change their `space` numbers to be base 5? 

Thanks in advance!

**Comment by jxnblk** [comment]
Thanks for the suggestion! Whereas margin and padding tend to change frequently on a per-instance basis, I don't often find the need to change small widths like this for the same component in different instances. Percentage based widths *are* something that tend to change on a per-instance basis. For the `PaginationDot` example above, there is the `size` function to control both width and height together. You can also use the `themeGet` utility to hard-code a width of `space[2]` in the component definition, but if you do really want a style prop for this, you can create your own custom style function: https://github.com/jxnblk/styled-system/blob/master/docs/api.md#customize

Overall, I don't suspect the use-case here is big enough to warrant adding more complexity to the current `width` function, if that makes sense

**Comment by lucastobrazil** [comment]
Ah yep, that makes sense! Will approach it that way. Thanks :)
