### ISSUE TITLE
How to use css pseudo element ?

### ISSUE THREAD

**Issue by vdesdoigts** [jxnblk/styled-system#304]
Hello, I can't figure out how to use css pseudo element, can you help me?  

i.e :
```
  <Button
    {...props}
    mx='auto'
    border='1'
    borderColor='transparent'
    fontWeight='400'
    borderRadius='20rem'
    css={{
      '&::after': {
        content: "",
        position: 'absolute',
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
        zIndex: -10,
        backgroundColor: '#000',
        borderRadius: 'inherit',
        opacity: 0,
        transition: 'inherit',
      }
    }}
  />
```

**Comment by k-sav** [comment]
So is it not possible to use a css pseudo element?

**Comment by jxnblk** [comment]
Guessing this might’ve been related to the `content` property https://theme-ui.com/object-styles#pseudo-elements

**Comment by k-sav** [comment]
Oh lawd. Thankyou!

**Comment by suvasishm** [comment]
Following https://theme-ui.com/guides/object-styles/#pseudo-elements,

I tried to use it like,
```
sx={{
  '&::before': {
       content: '"{' > '}"',
    },
}}
```
It produces error:
```
Unhandled Runtime Error
Error: You seem to be using a value for 'content' without quotes, try replacing it with `content: '">"'`
```

What is the correct way? It tried the suggested way, but that produces syntax error.  @jxnblk can you please help?

**Comment by suvasishm** [comment]
> Following https://theme-ui.com/guides/object-styles/#pseudo-elements,
> 
> I tried to use it like,
> 
> ```
> sx={{
>   '&::before': {
>        content: '"{' > '}"',
>     },
> }}
> ```
> 
> It produces error:
> 
> ```
> Unhandled Runtime Error
> Error: You seem to be using a value for 'content' without quotes, try replacing it with `content: '">"'`
> ```
> 
> What is the correct way? It tried the suggested way, but that produces syntax error. @jxnblk can you please help?

Fixed it by:

```
sx={{
  '&::before': {
    content: '" \u003E"',
  },
}}
```
