### ISSUE TITLE
Feature request: allow spacing function to take an object instead of (or as well as) an array

### ISSUE THREAD

**Issue by Joebourne** [jxnblk/styled-system#305]
If a design system uses lots of padding/margin values, the theme may contain an entry like this: `space: [ 0, 5, 10, 20, 25, 30, 35, 40, 45, 50, 60, 80, 100 ],`. 

If we require spacing of `60px` at our first breakpoint, `80px` at our second and `100px` at our third, the markup would look something like `<MyComponent mb={[10, 11, 12]} />`.

As `space` is an array, not an object with memorable keys, people would need to be familiar with the order of that huge array. Also if designers add another element to the array, you would have to refactor every use of `space`.

What we'd like to be able to do is write something like `<MyComponent mb='xl' />` and for the theme to map this key to values by media query, something like `space: { lg: [40, 50, 60], xl: [60, 80, 100] }`, though I know this will conflict with the current implementation where a string value is used as raw CSS. Would a `Symbol` work?

Would be good to hear your thoughts.

**Comment by jxnblk** [comment]
Objects should already work. If you're encountering any issues, please feel free to reopen.

I've added an example to demonstrate: https://codesandbox.io/s/github/jxnblk/styled-system/tree/master/examples/theme-aliases
