### ISSUE TITLE
Space scale - Look up by name

### ISSUE THREAD

**Issue by rafaelchiti** [jxnblk/styled-system#306]
Hey! first of all thanks for all the work here! I enjoy so much using this library!.

I was finding myself trying to give names to the space theming instead of using array positions.

Instead of:
```jsx
const theme = {
  space: [
    0, 4, 8, 16, 32, 64, 128
  ]
}

<Box m={[1, 4]}></Box>
```

Do:
```jsx
const theme = {
  space: { xs: 4, s: 8, m: 16, l: 32, xl: 64, xxl: 128 }
}

<Box m={["xs", "l"]}></Box>
```

And I wanted to do it at a low level so I could then build on top things like (by using styled-system `style` helper):

```jsx
<Box inset={["square-xs", "square-xl"]}></Box>
```

## Question
Is there an official way of defining aliases to those props in the theme that are responsive? or to hook into the look up logic to have our own?

## Current solution
So far I took advantage of how space is being used to look up for its values, so I switched it to an 'object literal' and added the 'indexes' as props as well as my aliases. But this seems fragile and might break if you consume spaces in a different way (since I imagine you expect an array there).

What I did:

```jsx
const spaces = {
  0: 0,  //
  1: 2,  // xs
  2: 4,  // s
  3: 8,  // m
  4: 16, // l
  5: 32, // xl
  6: 64, // xxl
};

spaces["square-xs"] = `${spaces[1]}px`;
spaces["square-s"] = `${spaces[2]}px`;
spaces["square-m"] = `${spaces[3]}px`;
spaces["square-l"] = `${spaces[4]}px`;
spaces["square-xl"] = `${spaces[5]}px`;
spaces["square-xxl"] = `${spaces[6]}px`;

spaces["squish-s"] = `${spaces[2]}px ${spaces[3]}px`;
spaces["squish-m"] = `${spaces[3]}px ${spaces[4]}px`;
spaces["squish-l"] = `${spaces[4]}px ${spaces[5]}px`;
spaces["squish-xl"] = `${spaces[5]}px ${spaces[6]}px`;

spaces["xs"] = `${spaces[1]}px`;
spaces["s"] = `${spaces[2]}px`;
spaces["m"] = `${spaces[3]}px`;
spaces["l"] = `${spaces[4]}px`;
spaces["xl"] = `${spaces[5]}px`;
spaces["xxl"] = `${spaces[6]}px`;

const theme = { space: spaces }
```

How I use it:
```jsx
<Box m={["l", "xl"]}></Box>
```

Or
```jsx
import { style, space } from "styled-system";
export const Box = styled.div(
  space,
  style({
    prop: "inset",
    cssProperty: "padding",
    key: "space"
  }),

<Box inset={["squish-s", "squish-xl"]}></Box>
```

**Comment by jxnblk** [comment]
I think there's a few things going on here, so not sure if this will answer you're question, but with the `theme.space` array, you can define aliases or additional values directly on the array (similar to what you have above)

```js
const space = [ 0, 4, 8, 16, 32 ]
space.big = space[4]
// Used like:
// <Box m='big' />
```

I'm not sure why the padding prop is being renamed to `inset`, but I generally wouldn't recommend using shorthand CSS syntax

**Comment by rafaelchiti** [comment]
Thanks!, yeap my bad, mixed a few things together. As for giving names to the space units, will do what you suggested. Im just curious if this is going to be a supported solution, since is not explicitly documented as part of the API.

Re: `inset`, maybe off topic but that is an attempt for having standard 'inset paddings' in my theme. I don't want developers to specify `px` `py` randomly I want them to use one of our pre built 'inset spacing conventions' while still taking advantage of responsiveness (inspired from here https://medium.com/eightshapes-llc/space-in-design-systems-188bcbae0d62. But I just realized I can use a new key in my theme and specify that when using the `style` custom utility. Anyway, if you have any thoughts on the topic, would appreciate your point of view.

Thanks! (feel free to close the issue)

**Comment by jxnblk** [comment]
> Im just curious if this is going to be a supported solution, since is not explicitly documented as part of the API.

This is more about how objects & arrays work in JS than anything specific to this library, so I wouldn't plan on breaking this functionality

Going to close this out since I think the original issue has been addressed
