### ISSUE TITLE
Possible issue with `in` operator in v3.1.9

### ISSUE THREAD

**Issue by jxnblk** [jxnblk/styled-system#311]
See rebassjs/rebass#510

**Comment by Lavoaster** [comment]
We're seeing it here.

**Comment by jxnblk** [comment]
Going to undo the changes in #297 until I can understand what's happening here – if anyone has time to look into this, that'd be super helpful

**Comment by jxnblk** [comment]
I've published v3.1.11, if anyone can confirm that this was the related change

**Comment by Lavoaster** [comment]
I can confirm this, `v3.1.11` fixes it.

**Comment by jxnblk** [comment]
Closing this out for now – a better `get` utility could be part of the next major release, but likely won't change the implementation in the near future
