### ISSUE TITLE
Is it possible use just one media query breakpoint change?

### ISSUE THREAD

**Issue by selrond** [jxnblk/styled-system#315]
in my `theme.js`:

```js
export const breakpoints = [
  '1000px',
]
```

my `Button.js`:

```jsx
import { space, fontSize } from 'styled-system'

export const Button = styled('button')`
  font-size: 1rem;
  ${fontSize}
`
```

usecase:

```jsx
<Button fontSize={['0.7rem', /* Use value (1rem in this case) from Button.js */]}>
  Login
</Button>
```

I know I can use `inherit` or so, but I want to be able to change default font-size globally in `Button.js`. 

If I used `fontSize={['0.7rem', '1rem']}`, and I decided later I want to change default button font size to `1.5rem`, I'd have to go through the whole app and replace the second breakpoint value.

Any elegant solution to this?

Thanks in advance

**Comment by jxnblk** [comment]
Not sure I 100% understand the question(s) here, but I'll try:
- Any number of breakpoints is acceptable & the first value in a props array will mean it's not scoped to a media query
- If you're wanting to set something both as a prop and as a default value, you can set `defaultProps` on the Button component, which would set the value for all Button components
