### ISSUE TITLE
Missing `flexGrow` and `flexShrink` styles

### ISSUE THREAD

**Issue by m0xx** [jxnblk/styled-system#318]
Hi!

Is there a reason why thoses style are missing? If not I can create a PR.

Thanks

**Comment by sarneeh** [comment]
I'm guessing that because it is recommended to use the `flex` property which contains `flex-grow`, `flex-shink` and `flex-basis` properties. @jxnblk correct me if I'm wrong.

**Comment by m0xx** [comment]
Yeah that make sense! I didn't know about this shorthand. Thanks

**Comment by jxnblk** [comment]
For now you can create custom props with the `style` function, which is the recommended way to handle things like this. I'll be working on making the docs clearer in this regard:

```js
const flexGrow = style({
  prop: 'flexGrow'
})
```
