### ISSUE TITLE
Docs on using responsiveStyle with boolean values

### ISSUE THREAD

**Issue by duro** [jxnblk/styled-system#32]
I have been typing to make sure of the responsiveStyle helper that ships with styled-system. That said, I'm trying to use it for a prop that is simply a true/false boolean, and needs change multiple properties when it is true.

Basically, I have a component that I want to switch between a mobile look and a desktop look, but delegate the breakpoint switching to styled-system.

I see that there is an argument on responsiveStyle for "boolValue", but it is not documented on exactly how it works.

Here is the way I am declaring my prop:

```
<LocationSelector width={350} fullWidth={[true, false]} />
```

And here is how I have implemented style styles:

```
export default styled.div`
  width: ${props => `${props.width}px`};
  ${responsiveStyle('width', 'fullWidth', '100%')};
  position: relative;
  z-index: 2;
`

export const StyledLSButton = styled.div`
  display: block;
  cursor: pointer;
  outline: none;
  border: none;
  border-bottom: 1px solid ${props => props.theme.lightMedGrey};
  ${responsiveStyle('margin', 'fullWidth', '0 15px')};
  padding: 0;
  height: 60px;
  background-color: transparent;
  position: relative;
  z-index: 4;
`

export const StyledLSOptions = styled.div`
  opacity: ${props => (props.open ? 1 : 0)};
  pointer-events: ${props => (props.open ? 'auto' : 'none')};
  transition: opacity 0.3s;
  background-color: white;
  top: -15px;
  box-sizing: border-box;
  left: -15px;
  right: -15px;
  ${responsiveStyle('width', 'fullWidth', '100%')};
  ${responsiveStyle('box-sizing', 'fullWidth', 'border-box')};
  ${responsiveStyle('left', 'fullWidth', '0')};
  ${responsiveStyle('right', 'fullWidth', '0')};
  padding: 85px 15px 15px;
  position: absolute;
  box-shadow: 0px 0px 4px rgba(0, 0, 0, 0.2);
  z-index: 3;
`
```

If I don't use an array for fullWidth, and I just toggle it between `<LocationSelector width={350} fullWidth />` and `<LocationSelector width={350} />` it works as expected, but not when I pass an array of booleans.

**Comment by jxnblk** [comment]
Sorry for not responding earlier. Since v2 no longer uses the boolean props option, I'm closing this out
