### ISSUE TITLE
Support calc for width

### ISSUE THREAD

**Issue by isitrita** [jxnblk/styled-system#320]
Hi, could you add support for calc function for width?

**Comment by jxnblk** [comment]
Any valid CSS string should work, e.g. `width='calc(100vw - 32px)'`

**Comment by matthova** [comment]
Would be great to figure out a way to combine key spacing with calc
For example: 
```
width="calc(100vw - 'm'px)"
```
I'm wondering if there's a clean way to pass in a spacing key/index to be parsed

**Comment by jxnblk** [comment]
@matthova you might want to look into custom style functions. The `transformValue` function is passed the theme `scale` as the second argument
