### ISSUE TITLE
TypeScript definitions for system-components

### ISSUE THREAD

**Issue by alexkrautmann** [jxnblk/styled-system#323]
I'm trying to use styled-system and system-components in a strict TypeScript project, but there are no available definitions for system-components. I've spent a few hours trying to write my own definitions for the module, but I am a beginner at TypeScript and struggling.

I noticed @phobon worked on the definitions for styled-system, maybe he is willing to help.

I do apologize for not being able to do this myself. I would have preferred to just submit a PR instead of filing an issue, but I am just not quite there yet with TypeScript.

**Comment by damassi** [comment]
`styled-components` is under `@types/styled-components`.

**Comment by alexkrautmann** [comment]
> `styled-components` is under `@types/styled-components`.

I'm talking about `system-components`, which is in this repo: https://github.com/jxnblk/styled-system/tree/master/system-components

**Comment by damassi** [comment]
Ah! misread that completely 👍

**Comment by jxnblk** [comment]
system-components is deprecated in favor of [@rebass/components](rebassjs/components), so I'd suggest adding definitely typed definitions for that package instead of the one here
