### ISSUE TITLE
Different responsive font sizes on different variants

### ISSUE THREAD

**Issue by sarneeh** [jxnblk/styled-system#325]
I'd like to create `Button` component with `normal` and `large` variants. Both of them would need different responsive `fontSizes`, like `[1, null, null, 2]` and `[2, null, null, 3]`.

I know that I can just do:
```js
const fontSize = props.large ? [2, null, null, 3] : [1, null, null, 2];
<Button fontSize={fontSize} />
```

But I wonder if there is any way to achieve the same result with `styled-system`'s `variant` function. Any suggestions?

**Comment by jxnblk** [comment]
Seems like your example code is fairly straightforward – not really sure what's wrong with that??

**Comment by sarneeh** [comment]
@jxnblk I guess I didn't explain it properly 😄 What I'd like to achieve is to move this configuration to the `theme` (button variants), like this:

```js
{
    buttons: {
        normal: {
            fontSize: [1, null, null, 2]
        },
        large: {
            fontSize: [2, null, null, 3]
        }
}
```

**Comment by jxnblk** [comment]
Variants only accept *style* objects, not *props* so the second example isn't supported. I would like to support a way to store responsive values in the theme (e.g. `fontSizes.large = [ 2, null, null, 3 ]`), but I don't think it's good to mix props with styles, if that makes sense. 

In your example, would these `normal` and `large` variants be used across a lot of different buttons?

**Comment by sarneeh** [comment]
@jxnblk You're right, that mix would be actually very confusing, didn't think about that.

Answering your question: not at all. I just wanted to move as many properties to `variants` as it's possible.

I think my question has been answered so I guess I can close this now 😄 Thanks for your replies!
