### ISSUE TITLE
[system-components]: Access theme values from `system` function

### ISSUE THREAD

**Issue by peduarte** [jxnblk/styled-system#329]
Hey 👋 

I've been using `system-components` and `mdx` quite a bit, and I love it.  Thanks so much for creating these awesome tools.

I've come across an issue where I wanted to get access to my custom theme from within the `system` function. 

I understand that `system` accepts a [custom function](https://github.com/jxnblk/styled-system/tree/master/system-components#using-custom-functions) but that raised some other issues.

I've simplified my use case to try try and illustrate what I'm trying to achieve.

Here's my issue:

I have a custom theme, with a `space` scale.
```js
const theme = {
  space: [10, 40]
}
```

I have an element, to which I want to add some CSS Properties based off of this theme.

```js
const H1 = system({
  is: 'h1',
  m: 1
})
```

So far so good 👍 
My `H1` Component is now being rendered as `h1` and it has `margin: 40px`.

Now I'd like to add some `border-bottom` to my element:

```js
const Title = system({
  is: 'h1',
  m: 1,
  borderBottom: '10px solid'
})
```

As expected, this also works. However, instead of hardcoding `10px` I'd like to be able to use my `space` scale, as I do for `margin`.

I understand `styled-system` provides a `themeGet` helper function, so I tried using that.

I've tried passing a function to `borderBottom`:
```js
const Title = system({
  is: 'h1',
  m: 1,
  borderBottom: `${() => themGet('space.0')}px solid`
})
```
But unfortunately this didn't work. I also tried: `${props => themGet('space.0')(props)}px solid`.

My second attempt, was to use the custom function approach, which looks like this:
```js
const Title = system(props => ({
  is: 'h1',
  m: 1,
  borderBottom: `${themeGet('space.0')(props)}px solid`
}))
```
So this kind of works, the dynamic border width is applied, but the `is` and `m` property are no longer working. (which sort of makes sense, given that this now just returning an object)

I understand I could replace `m` with `margin` and update its value to `${themeGet('space.1')(props)}px` but now I lost access to the elegant API.

I've created a [CodeSandbox demo](https://codesandbox.io/s/oqxopz4wy5) so you can see an interactive demo.

Anyway, would anyone have any better ideas? 

I'd love to hear your thoughts.

Thanks!

**Comment by flybayer** [comment]
Do it like this:

```js
const Title = system({
    is: 'h1',
    m: 1,
  },
  `
    borderBottom: ${props => themGet('space.0')(props)}px solid;
  `
})
```

The first `system()` argument is defaultProps. After that, any css strings are passed directly to `styled-components`.

Btw, `system-components` is now [`@rebass/components`](https://github.com/rebassjs/components).

**Comment by peduarte** [comment]
@flybayer hey 👊 

Ahhh, I've actually been using `system-components` this whole time. I've also been referring to [this docs](https://github.com/jxnblk/styled-system/tree/master/system-components).

I'm a bit confused now, maybe the API is different between `system-components` and `@rebass/components` but I had actually tried what you suggested, but that never worked.

I'm now giving @rebass/components` a go,  but that doesn't work either.

Are you able to provide me a working example?

**Comment by lucastobrazil** [comment]
Another syntax I"ve used is:

```js
const Title = system({
    is: 'h1',
    m: 1,
  },
  props => ({
    paddingLeft: props.avatarUrl ? themeGet('avatarSizes.small', '32px')(props) : '16px',
  })
})
```

**Comment by peduarte** [comment]
@lucastobrazil Thanks for your reply. In that case, I'll close this issue since `system-components` is no longer the recommended package. I created this issue on the `rebassjs` repo: https://github.com/rebassjs/components/issues/10 

Maybe if you're familiar with it you could help me over there?

Thanks 👊
