### ISSUE TITLE
don't output shorthand spacial props?

### ISSUE THREAD

**Issue by jessehart** [jxnblk/styled-system#33]
i see `p` and `m` props output `padding` and `margin`. for style merges i would expect space to export all 4 directions.

**Comment by Kikobeats** [comment]
Hey @jessehart, ca you write an example of what is hapenning right now and what is your expectation with this? It can help to put your words in context and be more clarify😄

**Comment by oomathias** [comment]
```js
const A = styled(Box).attrs({
  pb: 1
})``

const B = styled(A).attrs({
  p: 2
})``
```

B will have
```css
.B {
  padding: 16px;
  padding-bottom: 8px;
}
```

Since css props are [sorted](https://github.com/jxnblk/styled-system/blob/master/src/space.js#L19), `padding` will always be before `padding-direction`. I don't see a merge problem here. Unless you wanted for `B` that `padding-bottom` equal `16px`

**Comment by jxnblk** [comment]
CSS is certainly a weird language, and this library probably shouldn't use any shorthand properties at all. I guess my initial thinking was that if you were to use `p` you would expect the shorthand, and the sorting creates a somewhat common pattern you sometimes see in CSS where a shorthand property is immediately overridden by the regular property

**Comment by amcculloughflexera** [comment]
Apologies for commenting on a closed issue, but I think it makes more sense than opening another, somewhat related question - 

I noticed that the previously mentioned functionality also expands to when using defaultProps, which I find a little more annoying, for example - 

`<Box p={0} />`

and inside `Box.js` - 

```
Box.defaultProps = {
   pb: 1
}
```

the `p` prop never gets to override the defaultProp of `pb`

to your previous comment - 

> and this library probably shouldn't use any shorthand properties at all

should we avoid using the shorthand notation altogether?
