### ISSUE TITLE
Does recent styled-system require styled-components v4?  I'm having some issues with SC v3

### ISSUE THREAD

**Issue by vonwao** [jxnblk/styled-system#330]
I noticed the "as" parameter does not work.  I wonder if this is a feature of syled-componets v4?  

Also some other things seem wonky.  I can't get Flex component (as shown in Rebass) to work.  My Flex component renders as display=block for some reason

If this is the case, which version of styled-system do you recommend that will work best with styled-components v3?

**Comment by jxnblk** [comment]
The `as` prop is part of styled-components' API, not styled-system – styled-system doesn't have anything to do with React and should work with v2-v4 of styled-components
