### ISSUE TITLE
Should I be using `@rebass/components` instead of `system-components`?

### ISSUE THREAD

**Issue by peduarte** [jxnblk/styled-system#331]
Hey 👊

I recently created an issue on here regarding [system-components])(https://github.com/jxnblk/styled-system/tree/master/system-components) and @flybayer kindly commented warning me that `system-components` has now become [@rebassjs/components](https://github.com/rebassjs/components).

There's no mention of that neither on this repo or on the `@rebass/components` repo.

Since this repo has over 2k stars and seems to be quite popular, I think this should be clearly documented. 

Thanks

**EDIT**:
I just noticed there is a subtle mention on the `@rebass/components` repo:

![image](https://user-images.githubusercontent.com/372831/47851658-3e6c7a00-ddd1-11e8-8c5a-0ad701507a1c.png)

But until @flybayer's comment I didn't even know it existed. So perhaps it'd be a good idea to add the comment on here too?

**Comment by peduarte** [comment]
Also just came across [this issue](https://github.com/rebassjs/components/issues/4) which by the looks of it, it doesn't seem like much effort will be added into maintaining this library. Is that a fair assumption?

👊

**Comment by lucastobrazil** [comment]
I had the same situation in [this issue](https://github.com/jxnblk/styled-system/issues/313) too.

The [blog post](https://varun.ca/styled-system/) referenced in the styled-system readme also links to system-components, and I posted [this issue](https://github.com/winkerVSbecks/varun.ca/issues/8) to ask if he could change the blog post :)

Saw your post on the Spectrum channel too. Hoping to get the community more active there :)

**Comment by peduarte** [comment]
Yeah... I think this needs to be documented. @jxnblk happy to help. 

👊

**Comment by dmt0** [comment]
So what actually happened to `system-components`? I see the `rebass/components` repo is actually archived. Are the features from that lib merged into some other lib?
