### ISSUE TITLE
Using `is` with React components

### ISSUE THREAD

**Issue by lucastobrazil** [jxnblk/styled-system#332]
I can do this:
```
import {TextPrimitive} from './Text';'

const CardBodyText = system({
    extend: TextPrimitive,
    ...
});
```
and I can also do this:

`<Component is="button" />`;

But I cannot do this:

`<CardBodyText is={TextPrimitive} />`

Any reason why this shouldn't be used?

**Comment by lucastobrazil** [comment]
@flybayer that doesn't have the same function though as the `is` prop.

`extends` allows you to indeed 'extend' the pre-defined styled functions of another `styled-system` component, but the `is` allows you to replace the element that gets rendered.

To be a bit less abstract. the thing I'm trying to achieve at the moment is basically this:

```js
import { Link } from 'react-router-dom';
//...
const Button = system({
  is: 'button',
  ...
});

<Button is={Link} to="/guides" bg="white" color="primary" display="block">
  Guides
</Button>
```

So basically I have my Button component styled as a nice button, but if I want to use react router, then I need the component to be a `Link` component.

A workaround is to make the Link a child of the Button, but then I have unnecessary nesting.

With `styled-components` v4 you can use the `as={MyComponent` prop. Was hoping we might be able to do something similar here!

**Comment by jxnblk** [comment]
system-components is deprecated in favor of [@rebass/components](rebassjs/components), which should work better for this sort of thing
