### ISSUE TITLE
cant set 'width' values from theme

### ISSUE THREAD

**Issue by noko966** [jxnblk/styled-system#346]
export default {
    colors: {
      black: '#000e1a',
      white: '#fff',
      blue: '#007ce0',
      navy: '#004175'
    },
    width: ['10','20']
  }

using <Box  width={1} or width='1'
get converted to width 1px

**Comment by jxnblk** [comment]
The `width` function doesn't have a theme key (see https://github.com/jxnblk/styled-system/blob/master/docs/table.md), but you could create you're own style function
