### ISSUE TITLE
'color' prop doesn't get filtered out

### ISSUE THREAD

**Issue by smashercosmo** [jxnblk/styled-system#35]
```javascript
// Box.js
import React from 'react'
import styled from 'react-emotion'
import { space, width, fontSize, color } from 'styled-system'

const Box = styled('div')`
  ${space};
  ${width};
  ${fontSize};
  ${color};
`;

export default Box

// App.js
<Box color="red" p={12}>Hello</Box>
```

Then, when I check markup in chrome dev tools, I see
```html
<div color="red">Hello</div>
```

styled-system 1.0.0
react 16.0.0

**Comment by jxnblk** [comment]
You can use the (`removeProps`)[https://github.com/jxnblk/styled-system#remove-props] function, but really that is an issue with how `react-emotion` and libraries like that work – in a nutshell, they try to use a whitelist of HTML attributes, and `color` is an HTML attribute

**Comment by smashercosmo** [comment]
Got it. Thx.

**Comment by smashercosmo** [comment]
mmm... one more question: when I create custom responsive propery ('display' for example) it also doesn't get removed from props though it's not a valid html attribute. Is it also an issue with emotion?
```javascript
// Box.js
import React from 'react'
import styled from 'react-emotion'
import { responsiveStyle } from 'styled-system'

const Box = styled('div')`
  ${responsiveStyle('display')}
`;

export default Box

// App.js
<Box display={["block", "none"]}>Hello</Box>
```
Result:
```html
<div display="block,none">Hello</div>
```

**Comment by smashercosmo** [comment]
ping @jxnblk )

**Comment by oomathias** [comment]
You have to remove it yourself like any props.

You can do something like that
```js
import { omit } from 'lodash'
const Blacklist = (Component, blacklist) => (props) => {
  const next = omit(props, blacklist)
  return <Component {...next} />
}

const Box = styled(Blacklist('div', ['display'])`
  ${responsiveStyle('display')}
`;
```

**Comment by smashercosmo** [comment]
@oomathias Yeah, I know I can remove it, I'm just wondering, why it gets rmoved when a single value is passed, like display="none", but it doesn't get removed when an array is passed. But, yeah, that's probably an issue with emotion.
