### ISSUE TITLE
transformValue not working

### ISSUE THREAD

**Issue by zebapy** [jxnblk/styled-system#362]
Transform value changing z index to `px`

https://codesandbox.io/s/r7pznzymro

It's changing z index in styles to `30px`

It seems backwards that I should have to remove the px with transform value instead of adding it or is that the intended usage?

**Comment by zebapy** [comment]
removing `cssProperty` in style fixes it?...

**Comment by jxnblk** [comment]
This looks like a bug. One thing that looks off is that `cssProperty` should be a camel-cased string (`zIndex`)

Is the reason you're not using the built-in `zIndex` to have a theme scale? It seems like it *should* include one, but is an oversight of the current API.

**Comment by zebapy** [comment]
Ah I was interpreting it as normal css so z-index. I realize docs say camelcase now. 

And yes I want my theme to manage z indexes.
