### ISSUE TITLE
proptype warning for width prop

### ISSUE THREAD

**Issue by desaintvincent** [jxnblk/styled-system#364]
Defining a width prop as object (as shown [here](https://github.com/jxnblk/styled-system/blob/master/docs/responsive-styles.md)) throw a prop type Warning
```
Warning: Failed prop type: Invalid prop `width` supplied to `styled.div`.
```
Version: 3.2.0

exemple:
```
// theme.js
export default {
  breakpoints: {
    xsmall: 0,
    small: 600,
    medium: 1024
  }
}
```
```
import styled from 'styled-components'
import { width } from 'styled-system'

const Box = styled.div`
  ${width}
`
Box.propTypes = {
  ...width.propTypes,
}

[......]

<Box width={{ xsmall: 1, medium: 1 / 3 }}>foo</Box>
```

**Comment by jxnblk** [comment]
Thanks, looks like #341 landed, but the propTypes definition wasn't updated here: https://github.com/jxnblk/styled-system/blob/master/src/index.js#L8-L12
