### ISSUE TITLE
Responsive grid example?

### ISSUE THREAD

**Issue by hanoii** [jxnblk/styled-system#365]
I gathered that I can use this to build a responsive grid layout without going with rebass or rebass-grid, is that so?

Is there anywhere an example of how to accomplish this?

Is it just nesting boxes with proper props?

**Comment by Albert-Gao** [comment]
Should be as easy as this:

```javascript
// Box is your wrapped styled-system component
// see Rebass's codebase for an example
<Box width={[1, 1/3, 1/2]} />
```

Then the width should be responsive according to your `breakpoints` settings.

You don't need a predefined `<Grid>`, you just use the `<Box>` or whatever your wrapper container, and write the width as you go.

**Comment by jxnblk** [comment]
For reference here is Rebass Grid's [source code](https://github.com/rebassjs/grid/blob/master/src/index.js) in its entirety:

```js
import styled from 'styled-components'
import {
  space,
  color,
  width,
  fontSize,
  flexWrap,
  flexDirection,
  alignItems,
  justifyContent,
  flex,
  order,
  alignSelf
} from 'styled-system'

export const Box = styled('div')({
  boxSizing: 'border-box'
},
  space,
  color,
  width,
  fontSize,
  flex,
  order,
  alignSelf,
  props => props.css
)

Box.displayName = 'Box'

Box.propTypes = {
  ...space.propTypes,
  ...color.propTypes,
  ...width.propTypes,
  ...fontSize.propTypes,
}

export const Flex = styled(Box)({
  display: 'flex'
},
  flexWrap,
  flexDirection,
  alignItems,
  justifyContent
)

Flex.displayName = 'Flex'

Flex.propTypes = {
  ...flexWrap.propTypes,
  ...flexDirection.propTypes,
  ...alignItems.propTypes,
  ...justifyContent.propTypes,
}
```

**Comment by Grsmto** [comment]
If you want to use CSS Grid instead of Flexbox, you can check an example of usage [here](https://polymath-ui-develop.netlify.com/docs-grid).
The code is available [here](https://github.com/PolymathNetwork/polymath-apps/tree/develop/packages/new-polymath-ui/src/components/Grid).

**Comment by hanoii** [comment]
And I get now that Rebass Grid is just a simplified wrapper around this, so thanks @jxnblk for the link!

**Comment by Albert-Gao** [comment]
@hanoii you can make the container ‘wrap’ or you simply just wrap the second row into another Box. Rebass grid is not css grid, it’s flexbox underneath.

**Comment by jxnblk** [comment]
Generally speaking styled-system props and things like Rebass Grid are fairly low-level constructs around flexbox so they should work just like any other flexbox grid layout. Hopefully you've gotten enough direction from this issue's discussion but feel free to reopen this issue if needed
