### ISSUE TITLE
Whats the reason behind the shorthand syntax? Any way around it?

### ISSUE THREAD

**Issue by antoniojps** [jxnblk/styled-system#378]
First of all, this is not an issue and more of a discussion. 🤷‍♂️🎩

I really love this package and it would be perfect for a project I'm working on right now. The only thing that's preventing me from using it outside a personal context is the shorthand syntax for the margin, padding and background props. Why not use the pattern of camel casing css properties in javascript?

Is there anyway around this without forking the repository?

I want people to be able to read my code and immediately understand what the prop is doing "pt" and "mt" are semantically poor.

What i want to be able to do:
```jsx
<Box backgroundColor="tomato" paddingTop={4} margin={3}>
  This is a box
</Box>

```

**Comment by jxnblk** [comment]
This feature will be coming in v4 – I've explained the rationale for shorthand syntax in various places in the past, but it's become a fairly common convention in libraries like Tachyons, Bootstrap, etc. over the years
