### ISSUE TITLE
align-content

### ISSUE THREAD

**Issue by bbenezech** [jxnblk/styled-system#38]
> It helps aligning a flex container's lines within it when there is extra space in the cross-axis, similar to how justify-content aligns individual items within the main-axis.

Not as needed as the other 3, but it feels weird to have it out.
Values: `flex-start | flex-end | center | space-between | space-around | space-evenly | stretch `
Resources: 
 - https://css-tricks.com/almanac/properties/a/align-content/
 - https://developer.mozilla.org/docs/Web/CSS/align-content

**Comment by jxnblk** [comment]
Thanks! Not an intentional omission, and will likely add it. For others looking into this, the spec is a **much** better resource for understanding how flexbox works: https://www.w3.org/TR/css-flexbox-1/#align-content-property

**Comment by jxnblk** [comment]
There is now an `alignContent` utility in v2, along with a [few others](https://github.com/jxnblk/styled-system#table-of-style-props)
