### ISSUE TITLE
How to make textStyle responsive?

### ISSUE THREAD

**Issue by ng-hai** [jxnblk/styled-system#380]
I want to make my `Typography` component change `textStyle` based on `breakpoints` but it's not working

```jsx
<Typography textStyle={{ sm: 'body2', lg: 'body1' }}>
  {value.description}
</Typography>
```

I have to handle by adding more boilerplate code and using `display` prop

```jsx
<Typography display={{ sm: 'none', lg: 'block' }} textStyle='body1'>
  {value.description}
</Typography>
<Typography display={{ lg: 'none' }} textStyle='body2'>
  {value.description}
</Typography>
```

Is there any workaround?

**Comment by jxnblk** [comment]
Variant props do not support the array/object syntax. You can set responsive style objects in your `theme.textStyles.body1` object as an alternative

**Comment by webattitude** [comment]
> Variant props do not support the array/object syntax. You can set responsive style objects in your `theme.textStyles.body1` object as an alternative

How do you do that ?

**Comment by juhov** [comment]
For anyone else getting here trough Google. This is one way to handle `textStyle` based on `breakpoints`. This is extending the Rebass `Text` component.

```js
import styled from "styled-components"
import { Text as _Text } from "rebass"
import { textStyle, get, px } from "styled-system"

const createMediaQuery = n => `@media screen and (min-width: ${px(n)})`

export const responsiveTextStyle = props => {
  const { responsiveTextStyle = [] } = props

  const textStyles = get(props.theme, "textStyles", [])
  const breakpoints = get(props.theme, "breakpoints", [])

  const styles = []
  if (Array.isArray(responsiveTextStyle)) {
    styles.push(textStyles[responsiveTextStyle[0]])
    for (
      let i = 1;
      i < responsiveTextStyle.slice(0, breakpoints.length + 1).length;
      i++
    ) {
      const rule = textStyles[responsiveTextStyle[i]]
      if (rule) {
        const media = createMediaQuery(breakpoints[i - 1])
        styles.push({ [media]: rule })
      }
    }
  } else {
    for (let key in responsiveTextStyle) {
      const breakpoint = get(breakpoints, key, null)
      const media = createMediaQuery(breakpoint)
      const rule = textStyles[responsiveTextStyle[key]]
      if (!breakpoint) {
        styles.unshift(rule)
      } else {
        styles.push({ [media]: rule })
      }
    }
    styles.sort()
  }
  return styles
}

const Text = styled(_Text)`
  ${textStyle}
  ${responsiveTextStyle}
`

export default Text
```

Used like this:
```jsx
<Text textStyle="heading2" responsiveTextStyle={{ 2: "heading1" }}>Lorem</Text>
```

...or the same in array format:
```jsx
<Text responsiveTextStyle={["heading2","heading2","heading1"]}>Lorem</Text>
```

Note: The array format create styles for each breakpoint. With objects you can set styles for certain breakpoints.

**Comment by littlefengers** [comment]
If you're not using textStyle, you could also do responsive fonts this way:

`const StyledText = styled(RebassText)(
  variant({
    variants: {
      heading1: {
        fontSize: [
          tokens.TypeFontT1MobileSize,
          null,
          tokens.TypeFontT1DesktopSize,
        ],
        linedHeight: [
          tokens.TypeFontT1MobileLineHeight,
          null,
          tokens.TypeFontT1DesktopLineHeight,
        ],
      },
    },
  }),
);
`
