### ISSUE TITLE
Named breakpoints

### ISSUE THREAD

**Issue by xuopled** [jxnblk/styled-system#386]
Hello, 

I have a large codebase and if I need to add an additional breakpoint, I need to add a value from each prop using responsive values like `p={[0, 3, 5]}`.

I I could use named breakpoints like `p={{s: 0, m: 3, l: 5}}`, it could be much easier et flexible.

What do you think?

**Comment by jxnblk** [comment]
This is already supported: https://github.com/jxnblk/styled-system/blob/master/docs/responsive-styles.md#using-objects

**Comment by xuopled** [comment]
Thank you very much!
