### ISSUE TITLE
Component-scoped breakpoints

### ISSUE THREAD

**Issue by gregoralbrecht** [jxnblk/styled-system#389]
Hello 👋 I've been using `styled-system` for a while now and it's been great! I noticed I kept running into a use case that I wasn't able to find anything about: Sometimes I need component-scopes/component-specific/"local" breakpoints.

Instead of relying on global breakpoints completely, I'd love to be able to use breakpoints that are specific for a single component, e.g. a menu that needs more than the global breakpoints. Not sure if that's already possible and I've only missed it? Would love to get your opinion on that! :)

**Comment by jxnblk** [comment]
You can nest ThemeProvider components to set different themes (maybe just breakpoints) for a certain context. Otherwise, manually passing a `theme` prop might work, but haven't tried it

**Comment by StevenLangbroek** [comment]
> You can nest ThemeProvider components to set different themes (maybe just breakpoints) for a certain context.

@gregoralbrecht can confirm this works. We use this for all sorts of shenanigans, like legacy component interop and A/B testing color changes.

**Comment by gregoralbrecht** [comment]
@jxnblk @StevenLangbroek Thank you guys! Will try this approach. For some reason, I thought having multiple nested themes would be a bad thing, but I suppose it's fine for only the breakpoints.

**Comment by StevenLangbroek** [comment]
@gregoralbrecht it's fine for literally anything. An example:

We have, besides raw color values, a set of "semantic" aliases. Testing changing our primary orange (which has accessibility issues when white text is used on it) to purple, was as simple as:

```jsx
const overrides = {
  colors: {
    background: {
      primary: 'purple' // just an example
    }
  }
}

<LocalTheme overrides={overrides}>
	{*/ that's it! /*}
</LocalTheme>
```

**Comment by penx** [comment]
For anyone visiting this 3 years later 😄

If you want this functionality on a Box component without modifying the theme context:

```ts
type Breakpoints = {
  breakpoints?: ObjectOrArray<number | string | symbol> | undefined;
};

export const Box = styled('div')<SpaceProps & LayoutProps & Breakpoints>(
  props =>
    space(
      props.breakpoints
        ? {
            ...props,
            theme: {
              ...props.theme,
              breakpoints: props.breakpoints,
              disableStyledSystemCache: true,
            },
          }
        : props,
    ),
  layout,
);
```

disclaimer: I don't know the implications of disabling the cache, so proceed with care. If this is writing to the cache then perhaps it could mess up calculations elsewhere?
