### ISSUE TITLE
Access Active Breakpoint

### ISSUE THREAD

**Issue by steverecio** [jxnblk/styled-system#392]
I have a flexbox and I would like to reverse its flex direction depending on the breakpoint. I'm trying to achieve the ordering as below:

Desktop view:

| 1 | 2 |
| 3 | 4 |
| 5 | 6 |

Mobile (notice how 3 and 4 switch):

| 1 |
| 2 |
| 4 |
| 3 |
| 5 |
| 6 |

**Comment by jxnblk** [comment]
Possible duplicate of #374
