### ISSUE TITLE
Missing propTypes.borderColor

### ISSUE THREAD

**Issue by avaragado** [jxnblk/styled-system#45]
The `propTypes` export doesn't define borderColor, so the cleanElement HOC doesn't strip this prop and it's passed down to the styled element.

**Comment by Kikobeats** [comment]
Can you link soruce code line? Can we convert this into PR? 😄

**Comment by oomathias** [comment]
https://github.com/jxnblk/styled-system/blob/master/src/prop-types.js indeed do not include `borderColor`
