### ISSUE TITLE
Add a way to transform reponsiveStyle

### ISSUE THREAD

**Issue by Kikobeats** [jxnblk/styled-system#50]
I'm trying to add `max-height` prop, with a similar behavior than `width`:

```jsx
const cardHeight = responsiveStyle({
  prop: 'maxHeight',
  cssProperty: 'maxHeight'
})
```

The problem with this factory is that is not handling different units (pixels, rem, %, ...)

I saw how you do it at [src/width](https://github.com/jxnblk/styled-system/blob/master/src/width.js).

A simple way to reach this is providing a transformation method as function:

```jsx
const cardHeight = responsiveStyle({
  prop: 'maxHeight',
  cssProperty: 'maxHeight',
  transform: n => !num(n) || n > 1 ? px(n) : (n * 100) + '%'
})
```

What do you think?

**Comment by oomathias** [comment]
Would be a great addition, but don't forget the scale so we can also write

```js
transform: scale => n => neg(i) ? -1 * s[Math.abs(i)] : s[i] || i
// or
transform: _ => n => !num(n) || n > 1 ? px(n) : (n * 100) + '%'
```

**Comment by Kikobeats** [comment]
what means `scale` and why is necessary?

The thing that worries me is that you still need to load `num`, `px` util. They are non evident that they exists until you read the code.

In addition, `width`, is not using `reponsiveStyle` mixin, so my idea is add it for avoid repetitive code and centralize in one API function, but not sure if internally will be used.

**Comment by oomathias** [comment]
`scale` is used here https://github.com/jxnblk/styled-system/blob/master/src/responsive-style.js#L22

Also, `scale` is used by default, and not really documented. So if you happen to use `responsiveStyle` with a prop named `icon`, and have a `theme.icon` defined, `scale` will be used and that's maybe not what you want.

Example:

```js
const theme = {
  width: [0, 8, 16, 32]
}
const props = { 
  width: 1
}
const result = responsiveStyle('width')({ ...props, theme })
// result = { width: 8px }
// scale = [0, 8, 16, 32], n = 1, scale[n] = 8
```

While `numberToPx` is useful, `responsiveStyle` would be more powerful IMO if you could pass your own `sx`.
I agree that space, width, border, ... should be using `responsiveStyle` and a refactor would be welcome. I dunno what you think about that @jxnblk? 

I made a `parserFactory` that takes `props` like `{ p: 'padding', m: 'margin' }` and directions like `{ t: 'Top', x: ['Left', 'Right']` and make use of my own `responsiveStyle` which supports this transform behavior. 

I will try to put this part in a repo, and if it makes sense I could do a PR.

**Comment by AdamWagner** [comment]
@oomathias - would definitely be interested in seeing your version of responsiveStyle that can handle transforms.

**Comment by jxnblk** [comment]
Thanks for the suggestion! The library started without utilities like `responsiveStyle` so that's probably the reason for the not-so-DRY code there. I've thought about handling value transforms sort of like what you described above, but probably wasn't going to work on it until the next version – would definitely consider a PR for this as long as it doesn't introduce any breaking changes

**Comment by jxnblk** [comment]
The utilities in v2 now accept a `getter` option, which should handle this. Please let me know if you run into any issues
