### ISSUE TITLE
styled-components innerRef compatibility

### ISSUE THREAD

**Issue by oomathias** [jxnblk/styled-system#52]
See https://www.styled-components.com/docs/advanced#refs

```js
const A = styled(Box)``

const B = styled(cleanElement(A))``

const cleanC = cleanElement(A)
const C = styled(cleanC)``
cleanC.propTypes = { ... }
cleanC.styledComponentId = 'cleanElement'

const App = props => (
  <div>
    <A innerRef={node => console.log('A', node)}>A</A>
    <B innerRef={node => console.log('B', node)}>B</B>
    <C innerRef={node => console.log('C', node)}>C</C>
  </div>
)
```

```
A =log=> node
B =log=> null
C =log=> node
```

@jxnblk Would it be ok to add a static `styledComponentId` prop inside `clean-element.js`? Or you don't want any code related to third-party libraries inside this one.

**Comment by okonet** [comment]
I'm also facing this issue. Is there any work around at the moment?

**Comment by jxnblk** [comment]
Sorry for the delay on this. I would accept a PR to make `cleanElement` handle the `innerRef` prop if anyone wants to take a look at that.

**Comment by jxnblk** [comment]
With v2, I've moved cleanElement to its own package (https://www.npmjs.com/package/clean-element) and it *should* handle the `innerRef` prop. There's also a new [`clean-tag`](https://github.com/jxnblk/styled-system/tree/master/clean-tag) package (which needs better documentation) that's intended for use with styled-system and that should also handle the `innerRef` prop. I haven't tested these extensively, so feel free to reopen the issue if you run into problems with the new versions

**Comment by flybayer** [comment]
`innerRef` is not working with `system-components 2.0.2`.

As you can see here, I'm passing `innerRef` to the `system-component Styled(div)` My innerRef gets passed to `div` but not to `Clean.div` and therefore not to `input`.

<img width="644" alt="screen shot 2018-03-21 at 11 03 43" src="https://user-images.githubusercontent.com/8813276/37717803-ad18cbba-2cf7-11e8-9a17-07847e2ef28c.png">

I know you can't see all the props here, but I verified that my ref callback is stopping at `div`.

**Comment by okonet** [comment]
I'm still having this issue with 

```
├─ styled-components@3.3.0
├─ styled-system@2.2.5
└─ system-components@2.0.3
```

**Comment by okonet** [comment]
Here is the reproducible case: https://codesandbox.io/s/pppkvj9x3j

Looks like this:
![2018-05-28 at 09 07](https://user-images.githubusercontent.com/11071/40601764-a8f0b446-6256-11e8-8b97-b9d0c5a97b16.png)

**Comment by bebraw** [comment]
Looks like https://github.com/jxnblk/styled-system/pull/188/files#diff-2ce4dbe5dde8070d319f049a924e5623 solves this.
