### ISSUE TITLE
Applying spacing to properties other than margin and padding

### ISSUE THREAD

**Issue by juice49** [jxnblk/styled-system#53]
When I started playing around with `styled-system`, one of the first things I wanted to do was apply spacing to properties other than `margin` and `padding`. There are loads of properties this might be useful for: `top`, `right`, `bottom`, `left`, `grid-gap`, `text-indent`, etc.

At first I thought I might be able to do this with `responsiveStyle`, but  I don't think that's the case, and I couldn't find anything else included to do this.

I hacked something together based on `responsiveStyle`, providing an API like this:

```js
const FixedTR = styled.div`
  position: fixed;
  ${spaceStyle('pos', space => `
    top: ${space};
    right: ${space};
  `, 1)}
`

const App = () => (
  <FixedTR pos={[ 2, 3 ]} />
)
```

`spaceStyle` takes three arguments:

1. The property to read the scale from.
2. The function the space value is passed into, used to create the CSS rule/s at each breakpoint.
3. The default scale value.

It seems to work, but I haven't done a lot with it.

My question is; am I totally missing the point of `styled-system`? Is there a reason it doesn't do this already? It's possible this just isn't the intended use 😅. Or maybe there is a glaringly obvious way to do this, and I just didn't realise!

[Example](https://codesandbox.io/s/m71vzjr049).

The source for `spaceStyle`:

```js
import { util, constants } from 'styled-system'

const {
  get,
  arr,
  px,
  neg,
  num,
  breaks,
  media
} = util

const spaceStyle = (key, fn, defaultVal) => props => {
  const bp = breaks(props)
  const sc = get(props, 'theme.space', constants.space)

  const val = typeof props[key] !== 'undefined'
    ? props[key]
    : defaultVal

  return arr(val)
    .map(mx(sc))
    .map(fn)
    .map(media(bp))
    .reduce(merge, '')
}

export default spaceStyle

const mx = scale => n => {
  if (!num(n)) {
    return n
  }

  const value = scale[Math.abs(n)] || Math.abs(n)
  if (!num(value)) {
    return value
  }

  return px(value * (neg(n) ? -1 : 1))
}

const merge = (reduced, css) =>
  typeof css === 'string'
    ? reduced + css
    : merge(reduced, ` ${Object.keys(css)[0]} { ${Object.values(css)[0]} }`)
```

Thanks!

**Comment by maxdeviant** [comment]
@juice49 I haven't tested this out, but I imagine this would work:

```js
import styled from 'styled-components';
import { responsiveStyle } from 'styled-system';

const textIndent = responsiveStyle({
  prop: 'textIndent',
  cssProperty: 'textIndent',
  // Use the `space` scale from the theme.
  key: 'space'
});

const Indented = styled.div`
  ${textIndent}
`
```

**Comment by maxdeviant** [comment]
The above solution doesn't work, but this does:

```js
import styled from 'styled-components';
import { responsiveStyle } from 'styled-system';

const textIndent = responsiveStyle({
  prop: 'textIndent',
  cssProperty: 'textIndent',
  // This right here is the trick; it converts the value on the `scale` to a px value.
  numberToPx: true
});

const Indented = styled.div`
  ${textIndent}
`;
```

**Comment by juice49** [comment]
Hey @maxdeviant, thanks for the help!

I actually did try this, but as far as I can tell, it always results in the value passed being turned literally into pixels, rather than the corresponding value from the spacing scale.

i.e. `1` becomes `1px`, not the corresponding value from the spacing scale (`8px` on the default spacing scale).

[Quick example](https://codesandbox.io/s/olyjjnv7my).

**Comment by maxdeviant** [comment]
@juice49 Very possible that I was wrong about it pulling the value from the scale :sweat_smile:

I'll have a look at this more later. I think that if it doesn't currently work, I think the way to go would be adding another parameter to `responsiveStyle` telling it to map the value to a scale in the theme.

**Comment by juice49** [comment]
@maxdeviant Thanks! If you think that's a good solution, I'd be happy to take a look at putting a PR together for it.

**Comment by jxnblk** [comment]
To pick up values from your theme use the `key` argument. Example: https://github.com/jxnblk/styled-system/blob/master/src/border-radius.js

**Comment by maxdeviant** [comment]
Funnily enough, I had tried both `key` and `numberToPx` separately, but now I see that it requires both in order to work :smile:

```js
import styled from 'styled-components';
import { responsiveStyle } from 'styled-system';

const textIndent = responsiveStyle({
  prop: 'textIndent',
  cssProperty: 'textIndent',
  // Pull from the `space` key on the theme.
  key: 'space',
  // Converts the value from `space` to a px value.
  numberToPx: true
});

const Indented = styled.div`
  ${textIndent}
`;
```

**Comment by juice49** [comment]
Sorry I never followed this up! Thank you both for the help.
