### ISSUE TITLE
Uncaught TypeError After update with react 16

### ISSUE THREAD

**Issue by igoldny** [jxnblk/styled-system#56]
after update from 1.0.2 > 1.0.8
i get this error from styled-system code:
`
Uncaught TypeError: Cannot read property 'oneOfType' of undefined
`
any idea what may cause it?

**Comment by maxdeviant** [comment]
It sounds like it can't find `PropTypes `.

Can you make sure that the `prop-types` package exists in your `node_modules` directory?

**Comment by igoldny** [comment]
Yes, it's definitely related to PropTypes.
It exists and I'm using it in my react app.

**Comment by oomathias** [comment]
It may be related to another issue, so take a look at https://github.com/jxnblk/grid-styled/issues/51#issuecomment-336222958, make sure you don't have a wrong `resolve.modules`.

**Comment by igoldny** [comment]
oh, you right, I do have 'src' resolved.
but I'm using it to import from components folder by 'import from "components"' instead of 'import from "../../../components"'.
I'm sure there are lots of packages I'm using that use prop types and they don't have this issue.
maybe is something with styled-system config that in this case make this error?

**Comment by igoldny** [comment]
I think the issue is that "styled-system" have in src "prop-types.js" file that name the same as the package, any chance to change the name of this file?

**Comment by 440459012** [comment]
is this problem resolved? i have this error too.

**Comment by igoldny** [comment]
no, you need to remove 'src' from resolve.modules in webpack config if you want to use this package.
strange that i didn't came across this issue in any other package (and i have lots of them)
