### ISSUE TITLE
Using extras like borderRadius with components

### ISSUE THREAD

**Issue by babycourageous** [jxnblk/styled-system#58]
Hi there

Really enjoying using the style functions to unify the look of my site with these! But I'm having a bit of difficulty understanding how the extra props are used with existing components. In addition to importing any of them (i.e. `borderRadius`) I have included it as a prop in my component (a styled `Box` using `styled-components`. But there is no `border-radius` on my output. 

```
import styled from "styled-components";
import { Box } from "grid-styled";
import { space, borderRadius } from "styled-system";

const PerformanceTime = styled(Box)`
  display: inline-block;
  color: #fff;
  font-size: 12px;
  font-weight: 600;
  ${space};
`;

<PerformanceTime p={1} mb={1} borderRadius={1}>10:00pm</PerformanceTime>
```

I'm obviously missing something simple!
Thanks

**Comment by gragland** [comment]
You need to include ${borderRadius} within your PerformanceTime style, like you did with ${space}.

**Comment by babycourageous** [comment]
Thanks @gragland 

I originally had that as well. Tried putting it back just now but still nada. 
Should it just work or is there anything else I might need to do? All the base ones work great as is!

**Comment by gragland** [comment]
@babycourageous Ah okay, not sure then as I haven't used `borderRadius` yet.

**Comment by babycourageous** [comment]
@gragland thanks for your eye. Strangely I can't get any of those "extra" configurations to work on my components. Do I need a `styled-components` `Provider` with a `theme` prop by any chance wrapping up the App ?

**Comment by gragland** [comment]
@babycourageous Just tested `borderRadius` and it looks like it expects a px/em/rem value. It doesn't read from theme spacing.

**Comment by babycourageous** [comment]
Oh thanks for checking into that @gragland. That's too bad - was hoping to take advantage of some consistency there (like with `width` `margin` and `padding` props). 

Are you also a maintainer - both the `styled-system` and `rebass` docs and examples seem to have references to a `radius` or `radii` property in the documentation for theme and "extra props"

**Comment by gragland** [comment]
Ah yes it looks like it gets values from `theme.radii` instead of `theme.spacing`. Maybe creating your own borderRadius style prop would do the trick (haven't tested this):
```js
import { responsiveStyle } from 'styled-system'
const borderRadius = responsiveStyle({
  prop: 'borderRadius',
  cssProperty: 'borderRadius',
  key: 'spacing'
})
```

**Comment by babycourageous** [comment]
Thanks for all your help @gragland -- 

I do see it working as a pixel value (rather than pulling from the theme object as docs suggest). I'll keep this open for now since rewriting the `borderRadius` property that already comes with `styled-system` and `rebass` is probably not the intention of the library.

**Comment by gragland** [comment]
I think the solution would be to override the theme using `themeProvider` and add an array of px values to `theme.radii`. I think it's unlikely that `borderRadius` will be changed to read from `theme.spacing` since that would be a breaking change for existing users.

**Comment by jxnblk** [comment]
It sounds like most of the questions have been addressed here, but just adding a note that if you'd like to use something like `theme.space` for the `borderRadius` utility, you can always handle that in your own theme definition, e.g.:

```js
const space = [ 0, 4, 8, 16, 32, 64, 256 ]
const radii = space
const theme = {
  space,
  radii
}
export default theme
```

Feel free to reopen this issue if you have any other questions.

**Comment by babycourageous** [comment]
Thanks @jxnblk - That note is very helpful!
