### ISSUE TITLE
Flex basis

### ISSUE THREAD

**Issue by GazzaHazza** [jxnblk/styled-system#70]
Great library to start with!

Just curious, is it possible to be able to have the width be `flex-basis` instead of `width`? Or anything like that?

Thanks

**Comment by jxnblk** [comment]
The `width` utility will always handle the `width` CSS property, but there's no reason you couldn't make a `flexBasis` utility using one of these: https://github.com/jxnblk/styled-system#low-level-style-functions

**Comment by GazzaHazza** [comment]
Thats great, thank you! Love the library!
