### ISSUE TITLE
Typescript support for styled-system

### ISSUE THREAD

**Issue by t49tran** [jxnblk/styled-system#71]
Hi @jxnblk, do you have any plan for typescript support ? 

I use styled-system across projects at work and we use typescripts so we need to additional module declaration for `styled-system`. If you are planning to have typescript included as part of `styled-system` then I am more than happy to contribute.

**Comment by miketmoore** [comment]
@t49tran I was about to build a declaration file for styled-system locally, I'd love to help. If I successfully build one, I'll share. Would this go into http://definitelytyped.org/ ?

**Comment by t49tran** [comment]
Hi @miketmoore , I just like to know from @jxnblk if he has plan to have type definition as part of the library. Otherwise I think we can put one into definitelytyped. If you have one to share, it should be great.

**Comment by maxdeviant** [comment]
I have some [partial type definitions](https://gist.github.com/maxdeviant/cfed775121829eb02283347083915383) for `styled-system` that I've been working on, if someone wants to use them as a starting point.

**Comment by jxnblk** [comment]
I think type definitions should go in definitelytyped since I do not use Typescript, Flow, etc., and I suspect it will be easier for others to maintain separately from this codebase.
