### ISSUE TITLE
Container Queries?

### ISSUE THREAD

**Issue by loganpowell** [jxnblk/styled-system#75]
Trying to chart out a path of styling that allows me to "learn once, write anywhere" and zero-ing in on this library for theming. 

Would I be able to combine `styled-system` with [`react-component-queries`](https://github.com/ctrlplusb/react-component-queries)?

**Comment by jxnblk** [comment]
Seems doable. Looks like it'd be on your end to pass the appropriate props in as needed to any styled-component

**Comment by loganpowell** [comment]
Sweet. I'll give it a go!
