### ISSUE TITLE
Optional Wrapper Feature to convert units and/or use object based theme

### ISSUE THREAD

**Issue by JoshRosenstein** [jxnblk/styled-system#85]
I was tinkering around a bit and wanted to share a possible feature to your package. 
Originally by using an array and referencing the size by index i would need to remember what index my base size is located and if I ever change/add to my unit scales, i would have to refactor.

At first, i was wanting to create a wrapper function that would return x units away from the base value of spacing array.  
(example space:[item1,item2,baseSpacing,item3,item4], and if i passed in [0,1,2], would push ['baseSpacing units','item3 units','item4 units'] , slapping on the units was first a work around so your internal doesnt reference theme again. But then I realized i also created a solution another issue i was having(wanting to convert your functions response to rem units).

I then realized i could throw away my original mid-referencing function and  I can just create a wrapper that doesn't reference the original arrays, i can have it reference an object, so my keys dont change, but i can add more keys if need be, and also throw in an option to return which unit and do the conversion (still assuming all scales are in px)

So my proposal is having a utility function, or separate function that returns different unit. that way we can still have functions reference the theme internally and do conversion rather than do: 
Original:
import {spacing} from 'styled-system'
import theme from '../'
import rem from '../'
<box m=[rem(theme.spacing[1]),rem(theme.spacing[2]),rem(theme.spacing[3])]>
Separate Import:
import {spacingRem} from 'styled-system'
<box m=[1,2,3]>
or Wrappers:
import {spacing,wrapper} from 'styled-system'
styled.box`${wrapper(spacing)}`
<box m=[1,2,3]>

I think wrapper utilities would work the best since you can have a wrapper for all units, and have a wrapper to reference a keyed object instead of an array, which reroutes some internals.
 
Let me know if any of this is making any since, im fairly new to coding, so if you dont think its worth it, its probably not worth it ha.

Heres my messy sandbox ive been tinkering around with:
[![Edit StyledSystem Testing](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/q99ymlq036)

**Comment by JoshRosenstein** [comment]
Heres a bit clearer example:
[![Edit Styled-System Dev Redo](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l2lvqqvp77)

**Comment by JoshRosenstein** [comment]
Just saw the Getter addon for v2. Thank you!

**Comment by jxnblk** [comment]
Not sure I follow the entire proposal here, but does the `getter` option sort of cover what you meant?

Also it can help the readability of code snippets if you use backticks for formatted code: https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by selrond** [comment]
@jxnblk I was thinking about the same problem - what if the design changes, and I had to add another space / fontSize / letterSpacing into the array?

One "solution" to this is to add the value to the end of the array, but that quite suboptimal for apparent reasons.

How about supporting an object as well? That way we could do 

```js
const fontSizes = {
	body: 16,
	h1: 32,
	h2: 28	
}
```

and reference it accordingly:

```jsx
<Text fontSize="h2">
```

**Comment by selrond** [comment]
Dang... just realized I can already do exactly that... Sorry
